//package final_project;//commented out because i'm not using packages atm. comment back in when running on JACOB


//import final_project.Winnow;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Scanner;
import java.util.Set;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Arrays;
import java.util.Properties;

import edu.stanford.nlp.pipeline.*;
import edu.stanford.nlp.ling.CoreLabel;
import edu.stanford.nlp.util.CoreMap;
import edu.stanford.nlp.ling.CoreAnnotations.*;
import edu.stanford.nlp.ling.HasWord;
import edu.stanford.nlp.ling.SentenceUtils;
import edu.stanford.nlp.parser.lexparser.LexicalizedParser;
import edu.stanford.nlp.parser.shiftreduce.ShiftReduceParser;
import edu.stanford.nlp.process.CoreLabelTokenFactory;
import edu.stanford.nlp.process.DocumentPreprocessor;
import edu.stanford.nlp.process.PTBTokenizer;
import edu.stanford.nlp.tagger.maxent.MaxentTagger;
import edu.stanford.nlp.trees.Constituent;
import edu.stanford.nlp.trees.Tree;
import edu.stanford.nlp.ling.Word;
import edu.stanford.nlp.parser.nndep.DependencyParser;
import edu.stanford.nlp.trees.GrammaticalStructure;
import edu.stanford.nlp.trees.TypedDependency;
import edu.stanford.nlp.ie.AbstractSequenceClassifier;
import edu.stanford.nlp.ie.crf.*;
import edu.stanford.nlp.ling.CoreAnnotations;

/**
 * CS 5340
 * Final Project
 *
 * @author Jacob Luke and Bernard Serbinowski
 *
 */


class Freq_tuple {
	public int numerator;
	public int denominator;

	public Freq_tuple(int n, int d){
		numerator=n;
		denominator=d;
	}
	public void inc_both(){
		numerator++;
		denominator++;
	}
	public void inc_de(){
		denominator=denominator+1;
	}
	public Double get_doub(int cut_off, double min_val){
		//System.out.println(numerator+"  "+denominator+ " "+((double)(numerator))/((double)(denominator)));
		if(numerator<cut_off){
			return 0.0;
		}
		if(((double)(numerator))/((double)(denominator))<min_val){
			return 0.0;
		}
		return ((double)(numerator))/((double)(denominator));
	}
}

public class Incident_Selecter{
	private static HashMap<String, Integer> dict=null;
/*
	private static HashMap<String, Freq_tuple> freq_weapon=new HashMap<>();
	private static HashMap<String, Freq_tuple> freq_indv=new HashMap<>();
	private static HashMap<String, Freq_tuple> freq_org=new HashMap<>();
	private static HashMap<String, Freq_tuple> freq_tar=new HashMap<>();
	private static HashMap<String, Freq_tuple> freq_vic=new HashMap<>();
*/
	private static HashMap<String, Freq_tuple> freq_arson=new HashMap<>();
	private static HashMap<String, Freq_tuple> freq_attack=new HashMap<>();
	private static HashMap<String, Freq_tuple> freq_bombing=new HashMap<>();
	private static HashMap<String, Freq_tuple> freq_kidnapping=new HashMap<>();
	private static HashMap<String, Freq_tuple> freq_robbery=new HashMap<>();


	private static ArrayList<String> ignore_arson=new ArrayList<String>(Arrays.asList(""));
	private static ArrayList<String> ignore_attack=new ArrayList<String>(Arrays.asList(""));
	private static ArrayList<String> ignore_bombing=new ArrayList<String>(Arrays.asList(""));
	private static ArrayList<String> ignore_kidnapping=new ArrayList<String>(Arrays.asList(""));
	private static ArrayList<String> ignore_robbery=new ArrayList<String>(Arrays.asList(""));
							//private static ArrayList<String> ignore_arson=new ArrayList<String>(Arrays.asList("", "ATTENTION", "GROUPS", "TERRITORY", "NEAR", "SHOULD", "THING", "GENOCIDE", "THINK", "COMING", "YEAR", "TAKEN", "YOUR", "CARTRIDGES", "LIMON", "SEARCH", "'", "MUCH", "VARGAS", "DYNAMITED", "MEJICANOS", "DEPARTMENT", ",", "WHERE", "AN", "-", ".", "CABANAS", "1", "HOW", "AS", "2", "AT", "3", "4", "THUS", "6", "9", ":", "REQUESTED", ";", "ELLACURIA", "OUTSKIRTS", "?", "COMMANDO", "SAME", "DETERMINED", "A", "SHOWN", "CHANGED", "BE", "SET", "I", "SMALL", "BATTALION", "PRIEST", "BY", "PARTICIPATED", "COMMAND", "TURN", "KILLED", "JUL", "STATES", "SITUATION", "SUPPORTED", "MARTI", "CONTINUE", "VEHICLES", "SECURITY", "IGNACIO", "MACHINEGUNS", "DO", "AMMUNITION", "MAURICIO", "AREA", "COUNTRY", "PLACES", "VIOLENT", "EXPLOSIVES", "EL", "FOR", "PRESS", "DAMAGE", "GUERRILLA", "NEED", "DOING", "PASSAGE", "OCCURRED", "COORDINATING", "ARAUCA", "MOVEMENT", "NEIGHBORHOOD", "SUFFERING", "ABOUT", "CONTRIBUTE", "ACTIVITIES", "CENTERS", "WITH", "ACTION", "TRUCK", "HE", "STRONG", "TREACHEROUS", "INTERCEPTED", "NEGOTIATION", "BECAUSE", "CARRIES", "TOLD", "COLOMBIAN", "CARRIED", "IF", "VARIOUS", "IN", "MOTHER", "COUNTERATTACK", "IS", "IT", "FORCE", "EVEN", "MAY", "SQUADS", "HAVE", "AGENCIES", "MONSIGNOR", "AMBUSHED", "ACTIONS", "CADENA", "KM", "5TH", "NOVEMBER", "FIRST", "CITY", "LA", "PERMANENT", "PROVOKE", "ARMY", "CASUALTIES", "SINGLE", "WEST", "DEATH", "JOINED", "DEFINITELY", "EASTERN", "REPORTS", "ESPECIALLY", "COMRADES", "THEATER", "WILLINGNESS", "CEMETERY", "IMPORTANT", "WERE", "GASOLINE", "SOLDIERS", "TOOK", "READ", "INSTITUTE", "OIL", "MEN", "THREE", "NEIGHBORHOODS", "NO", "LOCATED", "LAND", "CITIES", "SAYS", "MEMBER", "OF", "STRIKE", "CHANGE", "COMMANDER", "CONFIRM", "ON", "ZACAMIL", "REPORTED", "SHOWED", "OR", "CONFRONT", "COLOMBIA", "ROMERO", "ATTACK", "SECOND", "THEIR", "GARCIA", "OLD", "BETWEEN", "FRONT", "THANK", "RIFLE", "POSITION", "INCREASE", "NOTHING", "MIDDLE", "KNOWLEDGE", "NORTHEASTERN", "MUST", "SPANISH", "EXPLOSIVE", "CALM", "STRATEGY", "ONE", "GROUP", "1ST", "U.S.", "MESSAGES", "SURRENDER", "DOES", "SO", "ALTHOUGH", "BUT", "SUCH", "GREAT", "SALVADORAN", "REBELS", "DELGADO", "CAME", "RESPONSIBILITY", "ALLIANCE", "OTHER", "PATROL", "MAINTAINING", "TO", "BEHALF", "UNION", "CANO", "THERE", "BEGINNING", "TRUTH", "APPROXIMATELY", "GUARD", "EXPLAINING", "GRENADE", "CORRESPONDENT", "UN", "UP", "DURING", "US", "PARTICIPATION", "SALVADOR", "THESE", "WORKING", "FINAL", "MEANWHILE", "WARN", "YEARS", "POSSIBLE", "PRIESTS", "LAST", "WROTE", "HOSPITAL", "IMPOSED", "STATIONED", "WHETHER", "INTERNATIONAL", "CONTROL", "GENERAL", "WE", "ACHIEVE", "SALVADORANS", "GUERRILLAS", "PIPELINE", "AREAS", "SHOT", "PROVIDE", "PAID", "TIME", "ANOTHER", "HOURS", "STRUGGLE", "PRESIDENT", "NEWS", "FILLED", "PEOPLE", "INSIDE", "RAMON", "PROBLEMS", "PLAN", "WOUNDED", "INCIDENTS", "WHEN", "FAILED", "BOTERO", "DOMESTIC", "OUR", "OUT", "GIVE", "GEN", "FIRED", "CONTAIN", "GET", "BRIGADE", "ARMORED", "ADVANCE", "PERSECUTION", "1989", "-LRB-", "PRESENT", "BEGIN", "STEPPED", "HOMES", "ORDER", "ADDED", "LIBERATION", "GIVEN", "BEING", "SEVEN", "MANUEL", "BOMBING", "NAMED", "MORE", "CONFRONTING", "CLANDESTINE", "0200", "SERVICE", "UNITS", "BOTH", "REGIONAL", "EXCEPT", "CAN", "AFRAID", "DETACHMENT", "CHURCH", "3,000", "PART", "ALSO", "RESULTED", "TIMES", "TODAY", "DIRECTION", "UNTIL", "ADDS", "STUDENTS", "KILLING", "MOVE", "TARGETS", "RESULT", "``", "HEARD", "VENCEREMOS", "ASSURANCES", "TANKS", "POLICE", "HELICOPTERS", "COMPLETELY", "UNIFORM", "CONTINUING", "DEMANDS", "BOMBINGS", "POLICY", "BEEN", "PAST", "STRATEGIC", "REITERATE", "THE", "LUIS", "BEGAN", "UNITED", "CONGRESS", "JOINT", "BARCO", "ARMED", "DEMOCRACY", "OFFENSIVE", "POWER", "PLACE", "GARRISONS", "OPERATION", "MINE", "ADMITTED", "INCREASED", "RECORDING", "DOWN", "ADMINISTRATION", "ELN", "PAZ", "ITS", "PAY", "TAKING", "GLORIOUS", "DEEPLY", "NORTH", "ENEMY", "FOUND", "TROOPS", "SOLDIER", "STATION", "NATIONALIST", "INSTALLATIONS", "EARLY", "FMLN", "TOWARD", "HEAVY", "HIGHWAY", "END", "DEFENSE", "AFP", "LEVELS", "DEPARTMENTS", "JUST", "SOME", "FOLLOWS", "CONCERNING", "''", "TERRORISTS", "CONDUCTING", "MORTARS", "OVER", "JESUIT", "OTHERS", "OFFICERS", "CRISTIANI", "BOARD", "FOUR", "RECEIVING", "TEXT", "'S", "CLAIMS", "INTERIOR", "WHICH", "ELSE", "FORCES", "LEFTIST", "SOUTH", "HOPE", "VERY", "NATIONAL", "COMMENTARY", "6TH", "AIR", "STILL", "HOWEVER", "LEADERSHIP", "ERP", "SAYING", "COUNTERINSURGENCY", "REVOLUTIONARY", "RIGHT", "FACTORY", "INTERVENTION", "PRESENTED", "MATERIAL", "CONTROLLED", "EFFORTS", "FARABUNDO", "VICENTE", "CALLED", "INTERVIEW", "-RSB-", "SIEGE", "THAT", "ATTACKS", "ALL", "TERRORIST", "ALONG", "RECEIVE", "HAPPENED", "ORGANIZATIONS", "SOVEREIGNTY", "TALKS", "MINUTE", "--", "DETACHMENTS", "MORAZAN", "TRUE", "JUSTICE", "POPULATED", "AND", "AGREED", "UNLEASHED", "ANY", "MAKE", "YSKL", "GOING", "STARTED", "MATERIEL", "BELIEVE", "ALFREDO", "NUNS", "LED", "COOPERATION", "CURRENTLY", "ATTACKING", "FREEDOM", "SCHOOL", "WEAPONS", "OWNED", "AFTER", "CLOSE", "ERNESTO", "PLURALISM", "THEY", "FIRE", "SABOTAGED", "FAITH", "INCLUDE", "10", "ENGINEERS", "ATTACKED", "18", "19", "SONORA", "TWO", "ANNOUNCEMENT", "REPUBLICAN", "ARE", "BOGOTA", "SOURCE", "MIGUEL", "THEM", "PARTY", "23", "26", "REPEAT", "PARTS", "2D", "ASK", "SEEK", "HILL", "36", "WORDS", "REPRESENT", "UNDER", "FIFTH", "OPEN", "CONTINUED", "3D", "EXPLOSIONS", "JOSE", "STAFF", "HAS", "CONTINUES", "INDISTINCT", "FIVE", "FAMILIES", "SEVERAL", "NUMBER", "CHIEFS", "KNOW", "FASCIST", "NOT", "NOV", "PLANE", "NOW", "-RRB-", "RIFLES", "THIS", "60", "UNIVERSITY", "OPERATIONS", "YES", "WAS", "PEACE", "WAY", "CAMPUS", "ARTILLERY", "CIUDAD", "SLOGANS", "REPORT", "WRITING", "PUT", "AGAINST", "PEREZ", "FAR", "CAPITAL", "HOMELAND", "89", "-LSB-", "MORNING", "CLASHES", "WORD", "TELEPHONE", "ARRESTED", "SUBMACHINEGUN", "THOSE", "MILITARY", "INDICATE", "WORK", "WITHOUT", "SO-CALLED", "POSTS", "COLONEL", "ARRIVED", "LARGE", "SPREAD", "COWARDLY", "DARK", "HIM", "HIT", "ADDITION", "OCCUPIED", "RADIO", "FEW", "DEVICES", "DAY", "DISLODGE", "M-16", "ONLY", "DEATHS", "FROM", "JESUITS", "SUPPORT", "POSITIONS", "HEADQUARTERS", "GUARDS", "WORLD", "WHO", "CONDUCTED", "SANDOVAL", "INTERVIEWED", "MEMBERS", "SINCE", "INFANTRY", "FIGHTING", "INDISCRIMINATE", "DATE", "CASTRO", "INJURED", "WIN", "SAN", "TRANQUILITY", "SAY", "SAID", "HERE", "COURAGE", "BURNED", "WEEK", "BASIS", "TOTAL", "INDUSTRY", "BAN", "THROUGHOUT", "CHIEF", "WILL", "WHILE", "GENERATE", "THEMSELVES", "YOU"));
							//private static ArrayList<String> ignore_bombing=new ArrayList<String>(Arrays.asList("", "ATTENTION", "DIRECTORATE", "GROUPS", "TERRITORY", "POOR", "AFFECTED", "NEAR", "FARC", "YEAR", "COMMUNIQUE", "TAKEN", "URGE", "ADVISABLE", "DEMONSTRATIONS", "$", "STOP", "'", "MIGHT", "VARGAS", "MEJICANOS", "DEPARTMENT", ",", "WHERE", "EMILIO", "-", ".", "CABANAS", "1", "2", "SEE", "3", "4", "5", "6", "7", "8", "9", "ADVISE", ":", ";", "ACHIEVING", "UNDERSTAND", "?", "SEP", "A", "RESPOND", "SET", "I", "FLORES", "BATTALION", "PARTICIPATED", "ATTRIBUTED", "JUL", "STATES", "JURISDICTION", "SUPPORTED", "MILLION", "CONTINUE", "VEHICLES", "SUSPEND", "RELATIONS", "SECURITY", "D'AUBUISSON", "COLINDRES", "STATEMENT", "SERVICES", "POST", "REPEATEDLY", "COOPERATE", "SHE", "PRISONERS", "COUNTRY", "NINE", "WITNESSES", "FINDING", "TONIGHT", "PLACES", "VIOLENT", "STRICT", "EXPLOSIVES", "HUMBERTO", "FOR", "DEPUTY", "USING", "NEED", "FOLLOWED", "DOING", "ATTAIN", "LIVES", "PASSAGE", "SIT", "OAS", "AMBASSADOR", "OCCURRED", "SIX", "COORDINATING", "BUSES", "WITHIN", "DEMANDED", "ACTING", "PROGRESS", "REACTION", "DETAINED", "OPINION", "CHARGE", "RODRIGUEZ", "WHITE", "BATTLE", "ATTEMPTED", "OCTOBER", "ACTIVITIES", "VIOLENCE", "CARLOS", "STATEMENTS", "RICA", "ACTION", "DESIRE", "FRG", "AGENTS", "PROVES", "CARACOL", "PLANNED", "TRUCE", "CANDIDATE", "NEGOTIATION", "UNDERSECRETARY", "GUILLERMO", "SEARCHING", "TOLD", "CARRIED", "SPOT", "BELIEF", "PABLO", "FORCE", "MSGR", "AUGUSTO", "FEBRUARY", "BECOME", "OPPOSITION", "AMBUSHED", "ACTIONS", "ASKING", "CEASE", "COUNCIL", "GACHA", "SPECIFICALLY", "ADDING", "5TH", "ENDED", "NOVEMBER", "THREAT", "COMMISSION", "SON", "CITY", "CLAIMING", "TREATED", "CREW", "CASUALTIES", "ALAN", "COLUMN", "FRENCH", "WILLING", "STATUS", "EASTERN", "WARNED", "REPORTS", "SECTORS", "RETURNED", "JANUARY", "COMRADES", "TRULY", "UNIT", "IMPORTANT", "DISCUSS", "AGREEMENT", "ASSASSIN", "TOOK", "READ", "INSTITUTE", "MAYOR", "OIL", "BEHIND", "ALLEGED", "REAL", "SPEAKING", "NEIGHBORHOODS", "COSTA", "NEIGHBORING", "INVITED", "EXTRADITABLES", "CHAMORRO", "FOLLOWING", "REPORTER", "HANDS", "LIBERAL", "VENEZUELA", "PRESIDENTIAL", "STRIKE", "CHANGE", "CONFIRM", "ANTONIO", "APRIL", "REPORTED", "MOMENT", "ELECTED", "CONFRONT", "COLOMBIA", "REBEL", "VISIT", "ROMERO", "MANAGUA", "RESOLVE", "ATTACK", "UNKNOWN", "BOSSES", "DOZEN", "IN-DEPTH", "WILLIAM", "BURIAL", "CIVIL", "GOVERNOR", "LEAST", "OLD", "OBSERVERS", "FRONT", "RIFLE", "CONSIDERED", "POSITION", "COMMUNITY", "PROCESS", "CIVIC", "SEEKING", "SOLIDARITY", "BRAZIL", "TRIAL", "MUNICIPAL", "ESTABLISHED", "SPANISH", "ANGRY", "KEY", "ACTS", "BEGUN", "CALL", "EMERGENCY", "CALI", "ATTENDED", "CARACAS", "ONE", "SUPPLIES", "RETURNING", "SUFFERED", "CLEARED", "MAOIST", "1ST", "BROUGHT", "BUT", "SUCH", "GREAT", "SALVADORAN", "HEADS", "FACILITIES", "CAME", "EVERYTHING", "RESPONSIBILITY", "...", "ALLIANCE", "OTHER", "REQUEST", "PERCENT", "COMMUNIST", "BEHALF", "VICE", "REVEALS", "HISTORY", "CANO", "EARLIER", "AIRCRAFT", "NEITHER", "CATHEDRAL", "FIERCE", "METROPOLITAN", "ALERT", "CLASS", "TECHNICAL", "BEGINNING", "VIEW", "LINES", "ACCOUNT", "GUARD", "ABSOLUTELY", "DURING", "COURTS", "CLASH", "SALVADOR", "SERVED", "WORKING", "TRAFFICKERS", "NAME", "YEARS", "VISTA", "TOWN", "HOSPITAL", "MEASURES", "BRING", "EXPERIENCE", "SOMOZA", "WHETHER", "INTERNATIONAL", "CONTROL", "ENTERED", "NARINO", "OFFICIALS", "IMPROVE", "NEGOTIATIONS", "GEORGE", "THOUGH", "GENERAL", "HIGHER", "JUDGE", "QUESTION", "ACHIEVE", "SIGNED", "NEXT", "SALVADORANS", "LEAVE", "PIPELINE", "SHOW", "LAUNCH", "PROVIDE", "LEFT-WING", "SERVING", "APPROACH", "REGARD", "WHAT", "GREEN", "URGENT", "AGENCY", "FMLN-FDR", "STRUGGLE", "0630", "DUTY", "PRESIDENT", "NEWS", "AGENDA", "GENOCIDAL", "MINUTES", "MEDELLIN", "UNIONS", "INSIDE", "UNTS", "1966", "DIRECTORS", "PROBLEMS", "NICARAGUAN", "PLAN", "RENE", "WOUNDED", "INCIDENTS", "PLAY", "WHEN", "YARD", "FAILED", "BREAK", "LOCAL", "DOCUMENT", "BOTERO", "RECOGNIZED", "PERSON", "DOMESTIC", "ENTERING", "LITTLE", "SUBJECTED", "OUR", "OUT", "CASE", "GIVE", "GEN", "AIMED", "1980", "GET", "SYSTEMS", "BRIGADE", "ADVANCE", "INVOLVE", "PERSECUTION", "SECRET", "ACCUSED", "STOLEN", "STAGED", "PRESENT", "BEGIN", "ROBERTO", "JOURNALIST", "DOLLARS", "SEVEN", "SENATOR", "CONDEMNED", "BOMBING", "PHYSICAL", "SPOKESMEN", "OWN", "MORE", "INVESTIGATORS", "SAENZ", "LIVING", "LIBERTY", "MORAL", "CONTACT", "PERSONALITIES", "ANNOUNCE", "SAFETY", "MEASURE", "USULUTAN", "CLANDESTINE", "SERIOUS", "AUXILIARY", "ALVARO", "STATED", "0200", "CONTINENT", "USED", "SERVICE", "STRONGLY", "BOTH", "DIFFERENT", "ANYONE", "KEEP", "MOST", "WEEKEND", "TRIED", "GRIPPED", "ITSELF", "CAN", "FLIGHT", "ESTABLISH", "FRANCISCO", "ARTURO", "URGED", "RELATED", "MURDERS", "DIED", "ASSUMED", "DETACHMENT", "GOMEZ", "ANGELES", "TREASURY", "ALSO", "INVOLVED", "SECONDLY", "SERIES", "TODAY", "CHAVEZ", "COMMENTED", "CHALATENANGO", "MEDIATE", "UNTIL", "ADDS", "TELLING", "KILLING", "MOVE", "DEVELOPMENT", "CROSS", "EDUARDO", "TARGETS", "SPOKESMAN", "APPROVED", "RESULT", "RIGHT-WING", "IMPLEMENTED", "SIMPLY", "UNDETERMINED", "TANKS", "POLICE", "VEHICLE", "COMBAT", "TRAFFICKING", "METHODS", "GMT", "TOGETHER", "MAKING", "NATIONS", "DELEGATIONS", "NATIONALITY", "EYES", "WHOM", "CRITICIZED", "THE", "LUIS", "BROKE", "KINGPINS", "SURROUNDED", "REGRET", "OBJECTIVE", "GOD", "JOINT", "BARCO", "ARMED", "PSYCHOLOGICAL", "RULED", "OFFENSIVE", "POWER", "PLACE", "MUNICIPALITY", "ANTIOQUIA", "EXTREME", "ABROAD", "REALLY", "DEAD", "ADMITTED", "SYSTEM", "EMBASSY", "DRIVER", "PAZ", "ISSUE", "NORTH", "CONSTANTLY", "MINISTRY", "ENEMY", "TROOPS", "CRITICAL", "RESPONSIBLE", "STATION", "NATIONALIST", "TOTALLY", "SOLVE", "BENITO", "CURRENT", "MEDICAL", "INDEPENDENCE", "FUENTES", "INCLUDED", "INDIVIDUAL", "CONDEMNING", "PRESSURE", "PEASANTS", "FOLLOWS", "''", "EXCLUSIVE", "TERRORISTS", "DISTURBANCES", "MORTARS", "IDENTIFIED", "SOCIALIST", "MEETING", "PROBABLY", "ILLEGAL", "OVER", "RELEASED", "BOARD", "COFFEE", "RANKS", "FOUR", "'S", "REACTED", "IMAGE", "CONFIRMED", "CLAIMS", "INTERIOR", "WHICH", "ELSE", "SOUTH", "MANNER", "VERY", "RAUL", "READY", "SENATE", "6TH", "GUILTY", "EITHER", "REGION", "HOWEVER", "TOP", "TOO", "CONGRESSMEN", "NARCOTERRORISTS", "ARGENTINE", "NEWSCAST", "FRIDAY", "REITERATED", "SAYING", "ALWAYS", "ORGANIZATION", "JUSTIFIED", "LARGEST", "LAUNCHED", "PURPOSE", "MATERIAL", "COL", "BETTER", "HONDURAN", "EFFORTS", "DEMONSTRATE", "FARABUNDO", "LAUNDERING", "HONDURAS", "PERHAPS", "VICENTE", "ORGANIZED", "SUSPENSION", "PROVE", "INTERVIEW", "BLOCKS", "REGIME", "-RSB-", "GETTING", "JORGE", "AFFIRMED", "LAS", "THAT", "ATTACKS", "ASSEMBLY", "RECENT", "LAW", "HIGH", "THURSDAY", "THAN", "WESTERN", "ALONG", "BUSINESS", "INSURGENTS", "UPCOMING", "TRY", "COMMANDERS", "CREATING", "--", "LEADERS", "OFFERED", "SAMAYOA", "NEGOTIATE", "BROAD", "JUSTICE", "POPULATED", "INFORMERS", "OTHERWISE", "DELICATE", "AGREED", "HEAD", "PAINFUL", "RIGHTS", "CARTEL", "INVESTIGATIONS", "REFUSED", "SOURCES", "YSKL", "COCA", "STARTED", "IMMEDIATELY", "MATERIEL", "INTERFERENCE", "MATTER", "COOPERATION", "FOURTH", "REACH", "AFTERNOON", "FREEDOM", "LET", "CONCERN", "LOGISTICS", "SIXTH", "CLOSE", "THEY", "MONTHS", "CENTER", "NEEDS", "INTERNAL", "10", "11", "12", "13", "14", "CUT", "15", "16", "ATTACKED", "DAILY", "17", "PROBLEM", "18", "19", "PROVIDED", "SONORA", "TWO", "ANNOUNCEMENT", "IDENTITY", "BOGOTA", "THEN", "THEM", "PROVIDES", "20", "BARRIOS", "21", "PARTY", "22", "23", "24", "25", "26", "27", "28", "RELIABLE", "CONFISCATED", "MERCEDES", "2D", "FISHING", "SUMMIT", "PREPARED", "SEEM", "30", "SEEN", "SEEK", "CONDUCT", "36", "WORDS", "HAD", "PREVENT", "CONTINUED", "3D", "JOSE", "GUTIERREZ", "HAS", "AGGRESSION", "CONTINUES", "TARGET", "45", "WANTED", "EXPLAINED", "INDISTINCT", "ORDERED", "DELEGATION", "POLITICIANS", "LEMOS", "REPORTERS", "50", "SEVERAL", "ENDURING", "FENASTRAS", "NUMBER", "RUNNING", "DECREE", "TUESDAY", "KNOW", "FERNANDEZ", "SOUTHERN", "LOWER", "SPECIFIC", "PLANE", "HOPEFUL", "-RRB-", "THIS", "EXAMPLE", "60", "HAVING", "UNOFFICIAL", "YES", "CHARGES", "CHARGED", "YET", "PEACE", "MEETINGS", "PANIC", "COL.", "CAMPUS", "CIUDAD", "GIVING", "72", "LIFE", "ISRAELI", "SLOGANS", "HOMILY", "REPORT", "PEASANT", "PUT", "RAFAEL", "HER", "PEREZ", "80", "CAPITAL", "89", "ASKED", "AIRPORT", "INCIDENT", "CEASE-FIRE", "EFFECTIVE", "ARMANDO", "INDICATED", "TABLE", "MORNING", "THREATENED", "HELD", "90", "CLASHES", "MPSC", "SATURDAY", "INTENSIFIED", "COME", "TYPE", "INDICATES", "RESULTING", "ARRESTED", "LIFT", "LEVEL", "THOSE", "LOS", "GOAL", "STRENGTHEN", "WITHOUT", "FATHERLAND", "CRIMES", "JAIME", "OPENED", "POSTS", "FLAG", "POLITICAL", "LARGE", "DOUBLE", "ENOUGH", "CAMPAIGN", "COWARDLY", "HELP", "SITE", "DARK", "ADVISERS", "HIM", "FAILURE", "HIT", "UCA", "HIS", "DAS", "FRAMEWORK", "NEARBY", "DAY", "LEAD", "DRUG", "FORMER", "STRICTLY", "ONLY", "DEATHS", "STRAFED", "RECEIVED", "SUPPORT", "POSITIONS", "EXPRESS", "GUARDS", "SECRETARY", "ESCOBAR", "WORLD", "CONDUCTED", "COMMENTING", "PANAMANIAN", "MEMBERS", "SUNDAY", "CONSTITUTION", "DATE", "LIKE", "GOES", "SENT", "GRENADES", "CONFLICT", "JOURNALISTS", "DELIVERED", "PANAMA", "MISSING", "SAID", "HERE", "STOPPED", "CONDITIONS", "WEEK", "DIRECT", "TOTAL", "ISSUED", "DEC", "SENATORS", "YORK", "MISSION", "DEL", "SERGEANT", "AMERICAN", "FORMS", "BEFORE", "LIMA", "THROUGHOUT", "CESAR", "ARTICLE", "DECLARE", "AREVALO", "WILL", "WHILE", "YOU", "UNDERSTANDING", "ENTERPRISES", "INVESTIGATING", "RULING", "YESTERDAY", "EVERYBODY", "DAWN", "SHOULD", "THING", "WHATEVER", "ARREST", "LEARNED", "HALF", "THINK", "COMING", "NORTHWESTERN", "INTENTION", "YOUR", "MURDERED", "CARTRIDGES", "PROPOSED", "REGRETTED", "PUNISHED", "LEFT", "SEARCH", "INFLICTED", "MUCH", "1230", "AM", "AN", "STRUGGLING", "HOW", "AS", "AT", "HOY", "THUS", "PERUVIAN", "RESISTANCE", "REQUESTED", "OUTSKIRTS", "PREVIOUSLY", "SAME", "LEAVING", "SHOWN", "BE", "TRYING", "REJECT", "DAYS", "HAND", "ROLE", "MESSAGE", "INSISTED", "BASED", "PERPETRATED", "BY", "COMMAND", "TURN", "INVESTIGATION", "KILLED", "DID", "BOXES", "DENIED", "SITUATION", "AIRPLANES", "MARTI", "REFERRING", "CENTENO", "NECESSARY", "NATURE", "CHANGES", "OFFICE", "DE", "RELIGIOUS", "DO", "DR", "CONFLICTS", "CONTROLLING", "AREA", "REPRESSION", "AUTONOMOUS", "ABANDON", "GOOD", "ALLOW", "CLERGYMEN", "AVIANCA", "EL", "LIGHT", "NACIONAL", "BUSINESSMEN", "PRESS", "GUERRILLA", "DECLARED", "ELECTRIC", "LIST", "LACK", "MARQUEZ", "STATE", "BASICALLY", "MOVEMENT", "BODIES", "NEIGHBORHOOD", "HUMANITARIAN", "SUFFERING", "ABOUT", "CONTRIBUTE", "ACTIVELY", "POINTED", "WELL", "GO", "7TH", "WITH", "SHORT", "ALREADY", "1,000", "WAGED", "AGAIN", "START", "FACING", "HE", "ROOM", "STRONG", "BECAUSE", "HIMSELF", "EVERY", "COLOMBIAN", "AIRPLANE", "ENFORCEMENT", "IF", "VARIOUS", "AMONG", "DEBATES", "IN", "AZCONA", "IS", "IT", "DPA", "ELECTIONS", "MAJ", "AGREE", "EVEN", "ACCUSATION", "MAN", "EVER", "MAR", "DEFEND", "MATTERS", "MAY", "TALKED", "SQUADS", "PLANES", "MASSACRE", "HAVE", "MONSIGNOR", "COMMENT", "THREW", "NEWSMAN", "CONFERENCE", "CADENA", "ARENA", "KM", "USE", "FIRST", "DIALOGUE", "ROSA", "PRIVATE", "MEANS", "LA", "SOCIAL", "HOLDING", "NORMAL", "LEGISLATIVE", "CONCLUDE", "ARMY", "SINGLE", "THIRD", "DETAILS", "DEATH", "PROPOSAL", "PEOPLES", "EVENT", "INTENTIONS", "MAFIA", "RESPECT", "DIFFICULTIES", "REPRESENTED", "FUEL", "VISITED", "ME", "ENJOY", "UPON", "ESPECIALLY", "WILLINGNESS", "CEMETERY", "WERE", "SEPTEMBER", "MY", "SOLDIERS", "RESIDENTS", "REMAIN", "DEMAND", "HAPPEN", "MEN", "DOZENS", "REASONS", "ELECTION", "LESS", "HELICOPTER", "THREE", "NO", "MAJOR", "LOCATED", "PERSONS", "LAND", "CITIES", "SAYS", "MEMBER", "DUE", "OF", "INVESTIGATE", "COMMANDER", "ON", "BELIEVED", "ZACAMIL", "PROMISED", "OR", "RIGHTIST", "MANEUVER", "BELIEVES", "ALLOWED", "AFFECT", "BUSH", "SECOND", "THEIR", "POINT", "OPPORTUNITY", "GARCIA", "MINISTER", "REACHED", "THROW", "BETWEEN", "DOCE", "ENSURE", "QUICKLY", "INCREASE", "CARRYING", "NOTHING", "MIDDLE", "EACH", "CERTAIN", "PREPARING", "MUST", "WANT", "WEAKEN", "BOLIVAR", "COMMUNICATIONS", "TELEVISION", "GROUP", "U.S.", "JAVIER", "DOES", "DESTROYING", "WOULD", "SO", "PONCE", "ALTHOUGH", "AROUND", "INTERESTS", "REBELS", "ARRESTS", "SOYAPANGO", "COMMITTEE", "COMMITTED", "CAPTURED", "PATROL", "0830", "THREATS", "MINISTERS", "MAINTAINING", "TO", "CALLS", "UNION", "MODERATOR", "THERE", "LATE", "HEREBY", "APPROXIMATELY", "PACKAGE", "EXPLAINING", "CORRESPONDENT", "UN", "JUAN", "UP", "US", "PARTICIPATION", "INNOCENT", "THESE", "RELATIVES", "DIEGO", "MEANWHILE", "FULL", "LAST", "CONSUMPTION", "VOTE", "COLOMBIANS", "CAUSING", "BELONGING", "BLAME", "WE", "PROTECT", "WAVE", "INITIATIVE", "HAPPY", "NEWSMEN", "GUERRILLAS", "SPOKE", "AREAS", "PERU", "BEHAVIOR", "SECTOR", "PAID", "TIME", "SOLUTION", "ANOTHER", "PERSONNEL", "HOURS", "FILLED", "PEOPLE", "SANTANDER", "POPULATION", "CRIME", "DIPLOMATIC", "VICTIMS", "CAUSED", "DICTATORSHIP", "CITIZENS", "TEGUCIGALPA", "REPUBLIC", "CENTRAL", "HERNAN", "BATTALIONS", "LEADING", "SOLUTIONS", "EVIDENCE", "OSCAR", "COMPANY", "RESIDENTIAL", "WOMEN", "COMMON", "PUBLIC", "SATISFIED", "EXACTLY", "-LRB-", "POLICEMEN", "ALPES", "QUITE", "STEPPED", "MRS", "ORDER", "ADDED", "LIBERATION", "GIVEN", "BEING", "BOLIVIA", "MANUEL", "ESCALATION", "DECIDED", "LOOKING", "PRELIMINARY", "COCAINE", "OFFICER", "MORALE", "NAMED", "STAYING", "SEIZED", "COULD", "BISHOP", "CUELLAR", "ASSOCIATION", "ACAN-EFE", "TELA", "EIGHT", "ZONE", "WASHINGTON", "UNITY", "MARXIST", "PATRIOTIC", "WOMAN", "ATTITUDE", "NATION", "THREATENING", "ERRAZURIZ", "TELL", "REPRESENTATIVE", "INCLUDING", "UNITS", "DONE", "SOUTHEAST", "MOVING", "BENAVIDES", "DEMOCRATIC", "DIFFICULT", "ACCEPT", "EXPLOITATION", "DEVELOPING", "MAINTAIN", "SPECULATIONS", "EFE", "ARIAS", "CHURCH", "FIRMLY", "PART", "SUBSTANTIAL", "SEARCHED", "EAST", "RESULTED", "CATHOLIC", "RESULTS", "25TH", "MEAN", "OFFICIAL", "DETERMINE", "LIEUTENANTS", "CERTAINLY", "JENNIFER", "PEDRO", "STUDENTS", "REESTABLISH", "ACCORDING", "``", "HEARD", "PATH", "VENCEREMOS", "DECEMBER", "PERFECTLY", "FIGHT", "SCHEDULED", "CLAIMED", "OPERATING", "EXPLAIN", "CANAL", "WALKER", "POINTS", "CHRISTIAN", "ATTEMPT", "COMPLETELY", "AMERICA", "COUNTRIES", "UNIFORM", "TECLA", "DEMANDS", "SABOTAGE", "HEART", "BOMBINGS", "BEEN", "EMPLOYEES", "SOMETHING", "CHILENA", "PAST", "JULY", "MURDER", "ANDRES", "TURBAY", "AGREEMENTS", "EXPRESSED", "CLARIFICATION", "DISTRICT", "BEGAN", "DAUGHTER", "WEARING", "TACTICS", "UNITED", "CONGRESS", "LABOR", "APPARENTLY", "AUTHORITIES", "MEET", "DETERMINATION", "SIMON", "DEMOCRACY", "SEEKS", "ABSTAIN", "NORTHERN", "RED", "250,000", "ACT", "OPERATION", "DESERVES", "MINE", "APPEARED", "INCREASED", "GOVERNMENT", "RECORDING", "DOWN", "ORLANDO", "ELN", "INFORMED", "ITS", "TAKING", "TALK", "OPPOSED", "LEADER", "DELEGATES", "DESERVE", "FOUND", "HOLD", "FACTS", "TAKE", "SOLDIER", "ENERGY", "CONSERVATIVE", "INSTALLATIONS", "INFORMATION", "EARLY", "FMLN", "WANTS", "TOWARD", "AK-47", "BLOODSHED", "HEAVY", "HIGHWAY", "APPROPRIATE", "GUATEMALA", "END", "CAPTAIN", "CONFUSE", "DEFENSE", "MONEY", "ECONOMIC", "DISCLOSE", "SANTIAGO", "QUESTIONED", "AFP", "DOCUMENTS", "JUST", "CLIPS", "SOME", "MAFIAS", "ACCUSATIONS", "CONCERNING", "CARIBBEAN", "SOVIET", "BRANCH", "ACCIDENT", "AGO", "OTHERS", "SOLE", "REPRESENTATIVES", "OFFICERS", "RIO", "BACK", "CRISTIANI", "TELEPHONES", "HOME", "PROTEST", "ADVISED", "RECEIVING", "TEXT", "ALMOST", "CONTINUOUSLY", "HUMAN", "PRESIDENTS", "FORCES", "LEFTIST", "AID", "SOON", "SPAIN", "DOUBT", "MOTHERS", "LOSSES", "NATIONAL", "ASSASSINATION", "WORKERS", "FIGHTERS", "AIR", "FORCED", "TORTURE", "STILL", "JARAMILLO", "BORDER", "VALDIVIESO", "MADE", "ADVISER", "ANNOUNCED", "ACCOMPANY", "ABLE", "FLYING", "ENTER", "ANDEAN", "POSSIBILITY", "OMITTED", "REVOLUTIONARY", "RIGHT", "TERROR", "ELENA", "ESCALON", "ANONYMOUS", "STARTING", "DISTRIBUTION", "MARTIN", "ANYWHERE", "EXCERPT", "ZACATECOLUCA", "DENYING", "CALLED", "PRESSURED", "ETA", "RICARDO", "EXTENSIVE", "WHOLE", "SIEGE", "OBSTACLES", "ALL", "NEW", "TRADE", "LETTER", "PUNISH", "FEEL", "TERRORIST", "ALIAS", "HOST", "FUTURE", "HOTEL", "PUBLISHED", "HAPPENED", "ORGANIZATIONS", "PACIFICATION", "JUDICIAL", "ORDERS", "FIND", "TALKS", "MINUTE", "MAIN", "ELITE", "TERRORISM", "ENTIRE", "TASK", "CLEARLY", "DESCRIBED", "MORAZAN", "4TH", "TRUE", "MARTINEZ", "PARTICIPATE", "THROUGH", "ANA", "AND", "SORT", "AUGUST", "MOUNTAIN", "INITIAL", "ANY", "MAKE", "FAMOUS", "REQUESTING", "GOING", "BARONS", "BELIEVE", "ALFREDO", "PERUANA", "DANGER", "POPULAR", "CURRENTLY", "ADVANTAGE", "MERE", "100", "SOTO", "VOICE", "PRESUMED", "ADMINISTRATIVE", "103", "SPECIALIZED", "JAN", "BLAMED", "EXPECTED", "CLEAR", "SCHOOL", "WEAPONS", "MONTH", "APR", "MENTIONED", "COUNTERPART", "MEDIATOR", "AFTER", "RAIDED", "EXCERPTS", "INDIVIDUALS", "WEDNESDAY", "AHEAD", "FIRE", "MORMON", "RESPONSE", "INCLUDE", "FIRM", "BLOOD", "LATER", "PRIOR", "REPUBLICAN", "SHOCK", "PALACE", "ARE", "THINGS", "SOURCE", "MIGUEL", "CORPS", "OBTAIN", "AFFECTS", "MOMENTS", "INTO", "REPEAT", "DECREED", "FACT", "RESIDENCE", "SPECIFY", "CONVERGENCE", "ASK", "LONG", "FELL", "REPRESENT", "CIVILIANS", "UNDER", "RUN", "PARTIES", "OPEN", "EXPLOSIONS", "PRESENCE", "MARCH", "LUISA", "STAFF", "MANY", "WEAPON", "FACE", "STAY", "SADNESS", "ELECT", "DESPITE", "ROUTE", "PERUVIANS", "DEARLY", "IMMEDIATE", "VICINITY", "FIVE", "AUG", "SUPPLY", "WHOSE", "DEMOBILIZATION", "SANTA", "BROKEN", "NETWORK", "GUERILLAS", "CHIEFS", "PROTECTION", "FELT", "LATIN", "CHILEAN", "FASCIST", "NOR", "THEREFORE", "ACADEMY", "NOT", "INTERNATIONALLY", "NOV", "GUARANTEES", "RANSOM", "SUSPENDED", "NOW", "PIZARRO", "RIFLES", "UNIVERSITY", "LOOK", "RICAN", "OPERATIONS", "WAS", "WAR", "SPEECH", "WAY", "REPRESENTS", "MASK", "SPREADING", "ADOPTED", "IMPLEMENT", "FOREIGN", "0500", "LEGAL", "EXECUTIVE", "RULE", "DIRECTOR", "CITIZEN", "EMPTY", "SOMETIMES", "SARMIENTO", "GENERALIZED", "STEP", "ESCAPE", "AGAINST", "VIRGILIO", "FAR", "CRIMINAL", "100-PERCENT", "-LSB-", "CUSCATLAN", "LOST", "STAND", "PRESIDENCY", "INTELLIGENCE", "THOUGHT", "GUNS", "INDISCRIMINATELY", "NICARAGUA", "DIRECTED", "FUNERAL", "ADVOCATED", "GAVIRIA", "WORD", "MARKET", "BULLETS", "CHILE", "MILITARY", "INDICATE", "DIARIO", "WORK", "CHECK", "ELECTRICITY", "SO-CALLED", "COLONEL", "ARRIVED", "EVIDENT", "FEDERATION", "PERSONAL", "DRUGS", "ESPECTADOR", "FEB", "PUPPET", "REACHING", "KNOWN", "PEACEFUL", "LAWYER", "NEGOTIATED", "ADDITION", "OCCUPIED", "RADIO", "FEW", "GOVERNMENTS", "DECISION", "EVENTS", "REFERRED", "CAUSE", "ARNULFO", "SENTENCE", "FROM", "M-19", "CARMEN", "SPECIAL", "HEADQUARTERS", "NIGHT", "MAZA", "PUTTING", "WHO", "SERIOUSLY", "SINCE", "WHY", "EXPERTS", "INFANTRY", "FIGHTING", "GOALS", "CHAIRMAN", "INRAVISION", "OCCUR", "WIN", "STEPS", "DECREES", "LINKED", "SAN", "CORDOBA", "FELLOW", "FESTIVITIES", "SAW", "SAY", "CONCERNED", "BASIC", "WAGING", "ACAN", "TOMORROW", "BURNED", "6-HOUR", "CALLING", "BOMBED", "BASIS", "RUBEN", "GROUNDS", "UNIDENTIFIED", "MEXICO", "INSTRUMENT", "CHIEF", "CIVILIAN", "THEMSELVES"));
							//private static ArrayList<String> ignore_kidnapping=new ArrayList<String>(Arrays.asList("", "ATTENTION", "GROUPS", "SURPRISE", "RULING", "YESTERDAY", "NEAR", "PASTRANA", "LEARNED", "HALF", "YEAR", "NORTHWESTERN", "COMMUNIQUE", "INTENTION", "TAKEN", "THOROUGHLY", "URGE", "LEFT", "$", "STOP", "SEARCH", "NEVERTHELESS", "'", "MIGHT", "DEPARTMENT", ",", "WHERE", "AN", "-", ".", "ATMOSPHERE", "STRUGGLING", "1", "HOW", "AS", "2", "SEE", "PROPOSALS", "AT", "3", "HOY", "VICTORY", "4", "5", "6", "PERUVIAN", "7", "8", "9", ":", "REQUESTED", "ACHIEVING", "OUTSKIRTS", "?", "SEP", "SAME", "LEAVING", "DETERMINED", "A", "RESPOND", "COVER", "SHOWN", "BE", "STRIKES", "TRYING", "SET", "DAYS", "I", "PREVIOUS", "FLORES", "MESSAGE", "BATTALION", "PERPETRATED", "PRIEST", "BY", "TURN", "KILLED", "DID", "ATTRIBUTED", "JUL", "`", "STATES", "JUN", "CIMA", "SITUATION", "MARTI", "MILLION", "CONTINUE", "NATURE", "VEHICLES", "SUSPEND", "RELATIONS", "OFFICE", "SECURITY", "COLINDRES", "STATEMENT", "DE", "ACTIVISTS", "SERVICES", "DETONATED", "DO", "SHE", "PRISONERS", "AREA", "COUNTRY", "REPRESSION", "ELIZABETH", "TONIGHT", "CAPTURE", "PLACES", "ASSASSINATIONS", "EXPLOSIVES", "EL", "LIGHT", "FOR", "NACIONAL", "PRESS", "GUERRILLA", "RADICAL", "ATTAIN", "LIVES", "HEADED", "DECLARED", "PASSAGE", "COMPANIONS", "PROPOSE", "OAS", "AMBASSADOR", "SIX", "STATE", "WITHIN", "LIVE", "DEMANDED", "ABSOLUTE", "ACTING", "INTERESTED", "MOVEMENT", "BODIES", "DETAINED", "NEIGHBORHOOD", "CHARGE", "ABOUT", "RODRIGUEZ", "OCTOBER", "WELL", "ACTIVITIES", "CASES", "WITH", "ALREADY", "CARLOS", "STATEMENTS", "ACTION", "GUADALUPE", "HE", "STRONG", "PLANNED", "OCT", "INTERCEPTED", "BECAUSE", "GUILLERMO", "TOLD", "COLOMBIAN", "CARRIED", "ENEMIES", "VARIOUS", "AMONG", "ESTRADA", "IN", "IS", "EXACT", "IT", "ATTEND", "PABLO", "DPA", "FORCE", "ELECTIONS", "MSGR", "WENT", "AUGUSTO", "CONDEMN", "MAR", "ARRIVE", "MAY", "MASSACRE", "HAVE", "FEBRUARY", "MONSIGNOR", "BLOODY", "COMMENT", "PLANNING", "ATTORNEY", "CARTAGENA", "CONFERENCE", "ACTIONS", "ASKING", "CADENA", "ASSOCIATED", "CEASE", "KM", "GACHA", "UNGO", "USE", "NOVEMBER", "FIRST", "CRIMINALS", "COMMISSION", "SHOOTING", "MEANS", "SON", "CITY", "LA", "SOCIAL", "LIBERTAD", "ABIDE", "DESTROYED", "TREATED", "HOLDING", "NORMAL", "LEGISLATIVE", "IDENTIFY", "CONCLUDE", "ARMY", "DETAILS", "ALAN", "COLUMN", "DEATH", "INTENTIONS", "RESPECT", "WILLING", "EASTERN", "REPORTS", "SECTORS", "ENJOY", "REASON", "ESPECIALLY", "JANUARY", "NUMBERS", "THANKS", "WERE", "SEPTEMBER", "DISCUSS", "AGREEMENT", "ASSASSIN", "SOLDIERS", "TOOK", "READ", "RESIDENTS", "REMAIN", "DEMAND", "OIL", "BEHIND", "MEN", "REAL", "LESS", "MET", "OCHOA", "THREE", "NEWSPAPERS", "NEIGHBORHOODS", "NO", "ACTIVE", "LOCATED", "PERSONS", "ROUTINE", "POLITICIAN", "FOLLOWING", "SAYS", "MEMBER", "REPORTER", "HANDS", "LIBERAL", "DUE", "OF", "INVESTIGATE", "VENEZUELA", "PRESIDENTIAL", "STRIKE", "ON", "ANTONIO", "BELIEVED", "ZACAMIL", "REPORTED", "SHOWED", "OR", "ASSISTANT", "PORRAS", "COLOMBIA", "REBEL", "VISIT", "TURNED", "BUSH", "ROMERO", "ATTACK", "THEIR", "UNKNOWN", "DOZEN", "POINT", "GARCIA", "MINISTER", "CONFIRMING", "LEAST", "BETWEEN", "FRONT", "COMMUNITY", "PROCESS", "CARRYING", "SEEKING", "EACH", "NORTHEASTERN", "MUST", "MUNICIPAL", "HELPING", "ESTABLISHED", "WEEKS", "WANT", "POINTING", "ACTS", "CALL", "CALI", "HIGHWAYS", "CARACAS", "ONE", "TELEVISION", "CEREZO", "SUFFERED", "GROUP", "1ST", "U.S.", "MESSAGES", "GALAN", "HECTOR", "DOES", "WOULD", "URIBE", "SO", "ALTHOUGH", "HEAVILY", "BUT", "SUCH", "SALVADORAN", "INTERESTS", "REBELS", "FACILITIES", "DELGADO", "CAME", "SOYAPANGO", "COMMITTEE", "LEARN", "RESPONSIBILITY", "OTHER", "CAPTURED", "FATHER", "PATROL", "THREATS", "BRITISH", "SUBJECT", "TO", "HIDING", "HISTORY", "THERE", "TECHNICAL", "BEGINNING", "0600", "APPROXIMATELY", "ACCOUNT", "TUPAC", "EXPLAINING", "UN", "JUAN", "UP", "DURING", "US", "SALVADOR", "SERVED", "THESE", "WORKING", "TRAFFICKERS", "RELATIVES", "DIEGO", "FINAL", "PRESUMABLY", "MEANWHILE", "FULL", "FURTHER", "NAME", "YEARS", "POSSIBLE", "LAST", "TOWN", "DEALT", "BRING", "EXPERIENCE", "WHETHER", "BOMB", "INTERNATIONAL", "COURT", "BILLION", "ENTERED", "OFFICIALS", "VOTE", "COLOMBIANS", "ASSASSINS", "GENERAL", "WE", "COURSE", "NOTES", "IMPLICATED", "ACHIEVE", "SIGNED", "NEWSMEN", "NEXT", "SALVADORANS", "GUERRILLAS", "SPOKE", "AREAS", "PERU", "PROVIDE", "NORTHEAST", "NOTED", "SECTOR", "MOUNTAINOUS", "TIME", "WHAT", "ANOTHER", "UNHARMED", "AWAY", "URGENT", "AGENCY", "PERSONNEL", "FMLN-FDR", "HOURS", "STRUGGLE", "0630", "PRESIDENT", "NEWS", "AGENDA", "PEOPLE", "MEDELLIN", "1966", "DIRECTORS", "POPULATION", "CRIME", "PROBLEMS", "SPEAK", "PLAN", "SHARE", "WOUNDED", "ENDING", "CARD", "CITIZENS", "WHEN", "FRANKLIN", "BREAK", "LOCAL", "DOCUMENT", "EXCHANGE", "ACTED", "PERSON", "CENTRAL", "1990", "DOMESTIC", "SUBJECTED", "OUR", "LEADING", "OUT", "CASE", "COMPANY", "GIVE", "WOMEN", "ESCORT", "SHERATON", "COMMON", "PUBLIC", "BRIGADE", "CAUSES", "PERSECUTION", "1989", "NAMES", "-LRB-", "POLICEMEN", "ANALYSIS", "BEGIN", "MRS", "ORDER", "ADDED", "LIBERATION", "GIVEN", "CEREMONY", "BEING", "ROBERTO", "JOURNALIST", "SENATOR", "ESCALATION", "DECIDED", "CONDEMNED", "BOMBING", "SPOKESMEN", "OWN", "BROTHER", "OFFICES", "STAYING", "MORE", "SEIZED", "COULD", "LIVING", "LIBERTY", "CUELLAR", "QUITO", "ACAN-EFE", "EIGHT", "ZONE", "MEASURE", "PATRIOTIC", "CLANDESTINE", "ALVARO", "INSTITUTIONS", "STATED", "0200", "INFORM", "REPRESENTATIVE", "MEDIA", "USED", "SERVICE", "INCLUDING", "STRONGLY", "UNITS", "CATATUMBO", "BOTH", "REGIONAL", "DIFFERENT", "SOUTHEAST", "MOST", "FULLY", "TRIED", "DEMOCRATIC", "CAN", "DIFFICULT", "ACCEPT", "EXPLOITATION", "FLIGHT", "KIND", "FRANCISCO", "DISCUSSIONS", "RELATED", "EFE", "HIRED", "SOCIETY", "HEADING", "CHURCH", "FIRMLY", "PART", "GOMEZ", "ALSO", "EAST", "MEAN", "OFFICIAL", "DETERMINE", "TODAY", "PESOS", "PEDRO", "UNTIL", "ADDS", "STUDENTS", "REST", "HUANCAYO", "REVEALED", "TARGETS", "SPOKESMAN", "RESULT", "ACCORDING", "``", "HEARD", "VENCEREMOS", "DECEMBER", "FIGHT", "MOREOVER", "SCHEDULED", "ECUADOR", "CLAIMED", "OPERATING", "TANKS", "SPORADIC", "POINTS", "POLICE", "CHRISTIAN", "HELICOPTERS", "AMERICA", "COUNTRIES", "COMBAT", "EFFECT", "REVEAL", "GMT", "TOGETHER", "SABOTAGE", "BOMBINGS", "POLICY", "BEEN", "EMPLOYEES", "SOMETHING", "PAST", "MAKING", "JULY", "RCN", "NATIONS", "ANDRES", "TURBAY", "EXPRESSED", "WHOM", "CLARIFICATION", "CLOSEST", "DOWNED", "REITERATE", "THE", "LUIS", "BROKE", "UPPER", "ALFONSO", "BEGAN", "DAUGHTER", "PARAMILITARY", "OBJECTIVE", "UNITED", "HEROIC", "BARCO", "ARMED", "VELASQUEZ", "AUTHORITIES", "DEMOCRACY", "POWER", "NORTHERN", "VINICIO", "PLACE", "VICTIM", "PERMIT", "MUNICIPALITY", "ANTIOQUIA", "ACT", "OPERATION", "ADMITTED", "GOVERNMENT", "RECORDING", "EMBASSY", "ADD", "DOWN", "INFORMED", "PAZ", "FASCISTS", "ITS", "PAY", "TAKING", "GLORIOUS", "TYPES", "LEADER", "HIGH-RANKING", "NORTH", "CONSTANTLY", "MINISTRY", "FOUND", "TROOPS", "TAKE", "RESPONSIBLE", "STATION", "INFORMATION", "EARLY", "FMLN", "TOTALLY", "OFFICIALLY", "BENITO", "WANTS", "SQUAD", "MEDICAL", "GUARANTEE", "GUATEMALA", "FOREIGNER", "END", "FUENTES", "INCLUDED", "CAPTAIN", "ORGANIZE", "DEFENSE", "MONEY", "ECONOMIC", "DISCLOSE", "SANTIAGO", "INDEPENDENT", "QUESTIONED", "AFP", "DEPARTMENTS", "JUST", "PRESSURE", "STUDENT", "SOME", "MAFIAS", "CONCERNING", "''", "EXCLUSIVE", "CONDUCTING", "IDENTIFIED", "AGO", "SOCIALIST", "MEETING", "ILLEGAL", "OVER", "OTHERS", "SOLE", "RELEASED", "REPRESENTATIVES", "OFFICERS", "LOPEZ", "BACK", "CRISTIANI", "BARRANCABERMEJA", "HOME", "PROTEST", "BOARD", "ADVISED", "ASKS", "FOUR", "JOIN", "RECEIVING", "TEXT", "'S", "ALMOST", "HUMAN", "IMAGE", "TRANQUILLITY", "CONFIRMED", "WHICH", "PRESIDENTS", "SICK", "FORCES", "SOON", "SPAIN", "DOUBT", "MOTHERS", "NATIONAL", "ASSASSINATION", "WORKERS", "GAVE", "FIGHTERS", "FORCED", "TORTURE", "EITHER", "AMARU", "REGION", "STILL", "JARAMILLO", "BORDER", "CONCEPT", "HOWEVER", "MADE", "ADVISER", "ANNOUNCED", "ACCOMPANY", "ABLE", "SAYING", "ENTER", "COUNTERINSURGENCY", "ALWAYS", "MONTANA", "ELECTORAL", "ORGANIZATION", "POSSIBILITY", "EFFORT", "LAUNCHED", "OMITTED", "REVOLUTIONARY", "RIGHT", "PURPOSE", "INTERVENTION", "ELENA", "FEBE", "ANYWHERE", "EXCERPT", "OLIGARCHY", "FARABUNDO", "CALLED", "SUSPENSION", "PRESSURED", "INTERVIEW", "KNEW", "-RSB-", "CONDEMNS", "JORGE", "THAT", "ATTACKS", "ALL", "NEW", "TRADE", "QUINTERO", "RECENT", "LAW", "HIGH", "PUNISH", "THAN", "TERRORIST", "ALONG", "BUSINESS", "HOTEL", "INSURGENTS", "ORGANIZATIONS", "MINUTE", "MAIN", "FINE", "ELITE", "TERRORISM", "--", "CRITERIA", "LEADERS", "OFFERED", "CLEARLY", "NEGOTIATE", "4TH", "TRUE", "PROOF", "BROAD", "COMMUNITIES", "EXISTING", "JUSTICE", "MARTINEZ", "PARTICIPATE", "REPORTEDLY", "POPULATED", "DEPARTURE", "THROUGH", "AND", "AUGUST", "REGISTRY", "RIGHTS", "CARTEL", "ANY", "MAKE", "SOURCES", "PUBLICITY", "IMMEDIATELY", "MATERIEL", "BARONS", "BELIEVE", "ALFREDO", "LED", "CURRENTLY", "FOURTH", "ADVANTAGE", "REACH", "VOICE", "SPECIALIZED", "JAN", "FREEDOM", "LET", "BEST", "EXPECTED", "WEAPONS", "MONTH", "APR", "ASSASSINATED", "OWNED", "LONGER", "AFTER", "COPREFA", "ERNESTO", "THEY", "INDIVIDUALS", "STREETS", "MONTHS", "CENTER", "WALDEMAR", "CONSIDERATION", "INCLUDE", "INTERRUPTED", "10", "11", "12", "LATER", "CAPACITY", "13", "14", "CUT", "15", "16", "DAILY", "17", "18", "PRIOR", "19", "OCCASION", "TWO", "ANNOUNCEMENT", "IDENTITY", "ARE", "THINGS", "BOGOTA", "SOURCE", "TAXI", "THEM", "PROVIDES", "CORPS", "OBTAIN", "20", "21", "PARTY", "22", "24", "INTO", "26", "27", "SHIPMENT", "PARTS", "OFFER", "29", "FACT", "FREE", "0700", "CONVERGENCE", "SUMMIT", "30", "SEEN", "SIMILAR", "LONG", "32", "CONDUCT", "ESSENTIAL", "CIVILIANS", "UNDER", "HAD", "ANALYZE", "PREVENT", "JOSE", "PRESENCE", "MARCH", "HAS", "PAYING", "MANY", "40", "CONTINUES", "45", "DESPITE", "WANTED", "INDISTINCT", "GATHERED", "IMMEDIATE", "MARIA", "INCREASING", "ORDERED", "DELEGATION", "FAMILIES", "LEMOS", "SUPPLY", "WHOSE", "SEVERAL", "NUMBER", "NETWORK", "GUERILLAS", "PROTECTION", "TUESDAY", "LATIN", "FASCIST", "THEREFORE", "ACADEMY", "NOT", "NOV", "GUARANTEES", "PLANE", "HOPEFUL", "NOW", "-RRB-", "THIS", "UNIVERSITY", "HAVING", "MARIO", "UNOFFICIAL", "VIOLATE", "OPERATIONS", "WAS", "YET", "PEACE", "WAR", "WAY", "PROTECTING", "RETURN", "ELEMENTS", "FOREIGN", "ARTILLERY", "LEGAL", "MASS", "EXECUTIVE", "DAMAGED", "CITIZEN", "LIFE", "VENEZUELAN", "SOARES", "ONES", "STEP", "REPORT", "WRITING", "SOACHA", "UNJUSTIFIABLE", "BROTHERS", "AGAINST", "JUDGMENT", "HER", "PEREZ", "VIRGILIO", "CRIMINAL", "CAPITAL", "89", "-LSB-", "ASKED", "AIRPORT", "CEASE-FIRE", "ARMANDO", "PRESIDENCY", "INTELLIGENCE", "MORNING", "THREATENED", "HELD", "NICARAGUA", "90", "COME", "INDICATES", "GAVIRIA", "WORD", "TELEPHONE", "HURTING", "REGARDING", "LEVEL", "THOSE", "MILITARY", "DIARIO", "WOUNDS", "LOSE", "WORK", "WITHOUT", "WIFE", "FATHERLAND", "SO-CALLED", "SMUGGLING", "PARTICULARLY", "COLONEL", "NOON", "ARRIVED", "BODYGUARDS", "SHOOT", "POLITICAL", "AMBUSH", "LARGE", "DRUGS", "RECENTLY", "CAMPAIGN", "COWARDLY", "HELP", "SITE", "SITUATIONS", "FEB", "KNOWN", "PEACEFUL", "LAWYER", "GUEVARA", "RESPECTIVELY", "HIM", "FRONTS", "HIS", "ADDITION", "OCCUPIED", "VERSION", "RADIO", "FEW", "ABOMINABLE", "DISLODGE", "DRUG", "DECISION", "FORMER", "CAUSE", "ARNULFO", "ONLY", "FROM", "SPECIAL", "INTEREST", "RECEIVED", "SUPPORT", "HEADQUARTERS", "DENSELY", "NIGHT", "SECRETARY", "WORLD", "WHO", "CONDUCTED", "COMMENTING", "MEMBERS", "SUNDAY", "THOUSANDS", "IRRATIONAL", "SINCE", "INFANTRY", "CONSTITUTION", "FIGHTING", "BLOW", "INDISCRIMINATE", "INRAVISION", "OPERATED", "DATE", "LIKE", "INJURED", "NOTIMEX", "SENT", "CIRCUMSTANCES", "SAN", "JOURNALISTS", "DELIVERED", "FELLOW", "PANAMA", "GUATEMALAN", "MISSING", "SAID", "HERE", "ACAN", "SPECULATION", "TOMORROW", "NOTE", "CHANNELS", "BASIS", "TOTAL", "ISSUED", "DEC", "GROUNDS", "MISSION", "UNIDENTIFIED", "CLARIFY", "OVERCOME", "MARXIST-LENINIST", "MEXICO", "AMERICAN", "BEFORE", "LIMA", "CESAR", "ARTICLE", "CHIEF", "RODRIGO", "WILL", "WHILE", "CIVILIAN", "THEMSELVES", "YOU"));
							//private static ArrayList<String> ignore_robbery=new ArrayList<String>(Arrays.asList(""));
							//ArrayList<String> ignore_attack=new ArrayList<String>(Arrays.asList(""));
							//private static ArrayList<String> ignore_attack=new ArrayList<String>(Arrays.asList("", "ATTENTION", "SIDEWALK", "NEAR", "INDICATION", "YEAR", "TAKEN", "URGE", "$", "STOP", "VARGAS", "DEPARTMENT", ",", "WHERE", ".", "CABANAS", "2", "3", "4", "5", "6", "7", "8", "9", "ADVISE", ":", "PROMINENT", "PASSENGERS", "SEP", "A", "RESPOND", "SET", "MAYORS", "FLORES", "BATTALION", "COMPANIES", "ATTRIBUTED", "JUL", "`", "JURISDICTION", "VEHICLES", "SECURITY", "COLINDRES", "SUBORDINATES", "WORTH", "SERVICES", "BOULEVARD", "ETERNAL", "SHE", "COUNTRY", "VIOLENT", "WORSE", "MECHANISMS", "SUPPLYING", "DOING", "JAIL", "BRAZILIAN", "PROPOSE", "OCCURRED", "WITHIN", "DEMANDED", "ACTING", "PROGRESS", "DETAINED", "CHARGE", "ACCOMPANIED", "RODRIGUEZ", "TRAVEL", "AIRES", "ACTION", "COORDINATOR", "DESIRE", "TRUCK", "RICH", "TRUCE", "TOLD", "AGUA", "AUGUSTO", "FEBRUARY", "STORMED", "ASKING", "ARGUMENT", "CEASE", "AVENUE", "SINCERE", "CASTILLO", "GUATEMALANS", "TRADITIONAL", "RECORDS", "SON", "2.5", "CASUALTIES", "ALARM", "COMRADES", "LONG-TERM", "IMPORTANT", "AGREEMENT", "TOOK", "200", "INSTITUTE", "PCCH", "HEARTFELT", "TOOL", "NEIGHBORHOODS", "ACTIVE", "SRE", "EXTRADITABLES", "CHAMORRO", "VENEZUELA", "REFERENCE", "STRIKE", "ANTONIO", "REPORTED", "SHOWED", "AFFECTING", "CONFRONT", "REBEL", "RESOLVE", "FRONT", "RIFLE", "CONTEXT", "CONSIDERED", "CONDOLENCES", "MISTAKEN", "FOREIGNERS", "SEEKING", "SLOW", "ESTABLISHED", "BOMBS", "ANGRY", "GRAY", "POSSIBLY", "SUFFERED", "MAOIST", "1ST", "MESSAGES", "SURRENDER", "MINISTRIES", "LANDING", "HECTOR", "HEAVILY", "BUT", "BUS", "VALLEJO", "RESPONSIBILITY", "OTHER", "PADILLA", "METROPOLITAN", "SORRY", "BEGINNING", "FINALLY", "1930", "GUARD", "GRENADE", "ABSOLUTELY", "DURING", "TRAFFICKERS", "TOWN", "MEASURES", "SOMOZA", "ENTERED", "SORTO", "BRIDGE", "HIGHER", "CREATES", "TWELVE", "PIPELINE", "PROVIDE", "AGENCY", "FMLN-FDR", "0630", "1960", "AGENDA", "SESSIONS", "MINUTES", "UNIONS", "INSIDE", "1966", "DIRECTORS", "WOUNDED", "INCIDENTS", "PLAY", "WHEN", "LOCAL", "DOCUMENT", "BOTERO", "PERSON", "1990", "DOMESTIC", "ENTERING", "SUBJECTED", "MONTOYA", "SYSTEMS", "NOTICE", "STAGED", "WONDER", "BEGIN", "CEREMONY", "ROBERTO", "JOURNALIST", "BOMBING", "PHYSICAL", "SPOKESMEN", "BROTHER", "REINFORCE", "SULA", "INVESTIGATORS", "INDEED", "ALVARO", "USED", "ANYONE", "EXCEPT", "GRIPPED", "ITSELF", "FLIGHT", "CAR", "SABOTAGING", "RELATED", "CLOSED", "DETACHMENT", "ANGELES", "SERIES", "TODAY", "COMMENTED", "UNTIL", "TELLING", "CROSS", "TARGETS", "SPOKESMAN", "ASSURANCES", "COLLABORATING", "SPORADIC", "INCLUSION", "COMBAT", "HURT", "DELEGATIONS", "WHOM", "CLOSEST", "APOPA", "PARDO", "CONSULT", "THE", "BROKE", "UPPER", "KINGPINS", "PROLONGED", "RECOVERING", "YOUTHS", "ARMED", "PSYCHOLOGICAL", "DRIVERS", "PLACE", "MUNICIPALITY", "ANTIOQUIA", "ADMITTED", "BARRANQUILLA", "FASCISTS", "DEEPLY", "MINISTRY", "GERMAN", "TROOPS", "SECRETARIAT", "OFFICIALLY", "MEDICAL", "UNILATERAL", "FUENTES", "HORDES", "RATE", "RECALL", "MINORS", "PRESSURE", "FOLLOWS", "SCENE", "INSIST", "''", "SOCIALIST", "PROBABLY", "ILLEGAL", "RELEASED", "FEELING", "FOUR", "'S", "REACTED", "CONFIRMED", "CLAIMS", "ELSE", "RAUL", "GUILTY", "EITHER", "HOWEVER", "TOP", "ARGENTINE", "FRIDAY", "ARGENTINA", "ORGANIZATION", "ABANDONED", "LAUNCHED", "USSR", "LAUNCHER", "DEMONSTRATE", "OLIGARCHY", "LAUNDERING", "VICENTE", "ORGANIZED", "SUSPENSION", "300", "-RSB-", "AFFIRMED", "LAS", "THAT", "ATTACKS", "LAY", "BUSINESS", "INSURGENTS", "UPCOMING", "315", "COMMUNIQUES", "CREATING", "--", "LEADERS", "OFFERED", "BROAD", "REPORTEDLY", "POPULATED", "INFORMERS", "AGREED", "HEAD", "CARTEL", "DISAPPEARANCE", "STORES", "MIRAFLORES", "COCA", "MUNICIPALITIES", "FOURTH", "LEG", "REACH", "LET", "CARABINEROS", "CONCERN", "REACT", "CLOSE", "COPREFA", "350", "STREETS", "MONTHS", "INTERNAL", "10", "12", "13", "14", "INJURIES", "DAILY", "18", "PROVIDED", "TWO", "ANNOUNCEMENT", "IDENTITY", "BOEING", "BOGOTA", "THEM", "PROVIDES", "20", "BARRIOS", "21", "PARTY", "22", "24", "CAMERAS", "27", "OFFER", "BUENOS", "TRAVELED", "0700", "2D", "CLOTHES", "SEEM", "30", "SEEN", "31", "32", "35", "BLEW", "36", "PENAL", "VOTING", "3D", "GUTIERREZ", "45", "47", "48", "GROWING", "INDISTINCT", "DECADE", "LEMOS", "NUMBER", "TUESDAY", "FERNANDEZ", "FORCING", "INTERSECTION", "PLANE", "-RRB-", "60", "64", "REDUCE", "BUILDINGS", "UNOFFICIAL", "CIUDAD", "SEIS", "VENEZUELAN", "ISRAELI", "SLOGANS", "REPORT", "80", "89", "AIRPORT", "ROLDAN", "ARMANDO", "TABLE", "THREATENED", "HELD", "INJURING", "90", "CLASHES", "ROOTS", "REJECTS", "AGRICULTURE", "LIFT", "LOS", "WIFE", "SOLELY", "ACHIEVED", "MOBILIZED", "LARGE", "ENOUGH", "SITUATIONS", "DARK", "GUEVARA", "DAS", "ABOMINABLE", "DISLODGE", "DRUG", "GERARDO", "RECEIVED", "SECRETARY", "INTERVIEWED", "INTERVENED", "CONSTITUTION", "OPERATED", "SENT", "DELIVERED", "MISSING", "FPMR", "RESTREPO", "HERE", "CHOICE", "COST", "NOTE", "STOPPED", "INCENDIARY", "TOTAL", "ORDERLY", "SENATORS", "SUPPOSED", "PERSIST", "LIMA", "CESAR", "ARTICLE", "GUILT", "AREVALO", "STUDYING", "CREDIT", "DAWN", "WONDERED", "THINK", "NORTHWESTERN", "THOROUGHLY", "CARTRIDGES", "SEARCH", "NEVERTHELESS", "INFLICTED", "1230", "AN", "THROWING", "STRUGGLING", "AT", "PERUVIAN", "RESISTANCE", "REQUESTED", "OUTSKIRTS", "PREVIOUSLY", "LEAVING", "SHOWN", "SUSTAINED", "BLUE", "MESSAGE", "CRASH", "INSISTED", "ORIGIN", "BY", "DETAILED", "TRANSPORTATION", "BRINGS", "IMPLACABLE", "DA", "DE", "ACTIVISTS", "CONFLICTS", "AREA", "BUSINESSMEN", "PRESS", "DAMAGE", "GUERRILLA", "RADICAL", "HEADED", "ELECTRIC", "LACK", "STATE", "RESPECTIVE", "BODIES", "NEIGHBORHOOD", "SUFFERING", "APPROACHED", "CELLS", "SUDDEN", "SHORTLY", "SUPPOSEDLY", "APPLY", "ACTIVITY", "INTERCEPTED", "AIRPLANE", "VARIOUS", "IN", "MOTHER", "MAN", "ALLOWING", "AGENCIES", "PLANNING", "THREW", "SPORTS", "NEWSMAN", "CADENA", "OUTSIDE", "KG", "KM", "LAUNCHERS", "DIALOGUE", "MEANT", "MEANS", "LA", "REBELLION", "HOLDING", "PERMANENT", "PROVOKE", "CONCLUDE", "ARMY", "SINGLE", "AYALA", "THIRD", "INTENTIONS", "MAFIA", "RESPECT", "ENJOY", "NUMBERS", "CEMETERY", "EXTEND", "SEPTEMBER", "MY", "EXTREMIST", "MEN", "ELECTION", "RHETORICAL", "CACERES", "OCHOA", "THREE", "EXISTENCE", "NEWSPAPERS", "NO", "INTERRUPTING", "BURY", "LAND", "DUE", "OF", "TRANSFORMER", "ON", "OR", "TIED", "BUSH", "OPPORTUNITY", "GARCIA", "CONFIRMING", "THROW", "BETWEEN", "ENSURE", "USUALLY", "QUICKLY", "CARRYING", "MIDDLE", "TOWER", "NORBERTO", "HIGHWAYS", "COMMUNICATIONS", "TELEVISION", "JAVIER", "BANKS", "DAUGHTERS", "CONFORM", "URIBE", "INTERESTS", "REBELS", "COMMITTEE", "0830", "MAINTAINING", "HEREBY", "COMMITS", "TUPAC", "UN", "PERQUIN", "RELATIVES", "OPPOSE", "FINAL", "WARN", "ROCKET", "LAST", "VOTE", "COMPLICATE", "CAUSING", "NEWSMEN", "GUERRILLAS", "SPOKE", "AREAS", "PERU", "APPEARS", "OBVIOUSLY", "OPERATE", "DESTABILIZING", "TIME", "QUESTIONS", "HOURS", "SECTION", "ECONOMY", "DIPLOMATIC", "FIGHTER", "ENDING", "CONSULATE", "HOUSE", "PREVENTION", "HERNAN", "COMPANY", "LAWS", "USUAL", "SATISFIED", "-LRB-", "STEPPED", "MRS", "LIBERATION", "BEING", "COCAINE", "OFFICER", "OFFICES", "STAYING", "SEIZED", "QUITO", "ASSOCIATION", "DRUGSTORE", "MARXIST", "WOMAN", "THREATENING", "PREPARATION", "SOUTHEAST", "BENAVIDES", "DEVELOPING", "POWDER", "PARTICIPANTS", "SPECULATIONS", "EFE", "POLICEMAN", "INTENSITY", "MINOR", "3,000", "JEOPARDIZING", "SUBSTANTIAL", "RESULTED", "25TH", "MEAN", "OFFICIAL", "INTENSIVE", "STUDENTS", "VIA", "SURRENDERING", "ACCORDING", "``", "VENCEREMOS", "PERFECTLY", "SCHEDULED", "CHRISTIAN", "BETANCUR", "VELEZ", "SABOTAGE", "BOMBINGS", "CHILENA", "JULY", "ABORTED", "CLARIFICATION", "HOSPITALS", "CARGO", "WEARING", "TACTICS", "CONGRESS", "SEEKS", "OPERATION", "DESERVES", "MARCOS", "INCREASED", "ELN", "TAKING", "CONDEMNABLE", "REQUIRES", "HOLD", "INSTALLATIONS", "TOWARD", "CARTRIDGE", "CAPTAIN", "MONEY", "ECONOMIC", "DISCLOSE", "QUESTIONED", "JUST", "CLIPS", "MAFIAS", "CONCERNING", "BRANCH", "OBTAINED", "LOGISTICAL", "INFILTRATED", "SOLE", "INTEGRATION", "HOME", "ADVISED", "SONS", "SIMEON", "DISTORT", "SOON", "LOSSES", "WORKERS", "FIGHTERS", "TORTURE", "ADVISER", "ACCOMPANY", "ABLE", "ENTER", "BROADER", "ALAMEDA", "ELENA", "ENGLISH", "EXCERPT", "ZACATECOLUCA", "MOUTHPIECE", "PRESSURED", "EXTENSIVE", "AIDES", "TERRORIST", "BUILD", "DATED", "HOTEL", "BRASILIA", "CORDONED", "FIND", "CRITERIA", "SHOWING", "TASK", "UNARMED", "CLEARLY", "MORAZAN", "4TH", "PARTICIPATE", "THROUGH", "AUGUST", "MOUNTAIN", "PUBLICITY", "REQUESTING", "PINOCHET", "PERUANA", "PRETEXT", "POPULAR", "CURRENTLY", "ADVANTAGE", "SOTO", "VOICE", "ADMINISTRATIVE", "SPECIALIZED", "EXPECTED", "DESIGNATED", "MENTIONED", "AFTER", "HOUSES", "EYE", "FIRE", "FIRM", "LATER", "EVACUATING", "0930", "SHOCK", "SOURCE", "MIGUEL", "SIMULTANEOUSLY", "REPEAT", "VOICED", "UNDER", "FIFTH", "PRESENCE", "WEAPON", "INCREASING", "FIVE", "FAMILIES", "PRIMARILY", "SUPPLY", "WHOSE", "LATIN", "HIDDEN", "FASCIST", "THEREFORE", "NOW", "WAS", "WAR", "CHURCHES", "WAY", "REPRESENTS", "SPREADING", "FOREIGN", "DAMAGED", "EMPTY", "GENERALIZED", "PARTIAL", "WRITING", "VLADIMIR", "JUDGMENT", "OLIGARCHIC", "100-PERCENT", "-LSB-", "CUSCATLAN", "GUNS", "UPSET", "ALTERNATIVE", "MARKET", "USEFUL", "CHECK", "MOSCOW", "ARRIVED", "SHOOK", "SHOOT", "FEDERATION", "SURPASSED", "ESPECTADOR", "FEB", "BRIEFING", "PASSERSBY", "ONGOING", "LAWYER", "AMAZONIA", "ADDITION", "OCCUPIED", "RATHER", "FEW", "GOVERNMENTS", "DECISION", "EVENTS", "FROM", "NIGHT", "PUTTING", "POLE", "REMOVED", "SLIGHTLY", "BLOCK", "CHAIRMAN", "INRAVISION", "DANGEROUS", "BLOCS", "CLEARING", "BATHROOM", "INJURED", "WIN", "COURAGE", "JAPAN", "BURNED", "CALLING", "RODRIGO", "TERRITORY", "LOYALTY", "FARM", "CONSOLIDATED", "LIMON", "CONTRIBUTION", "ACHIEVING", "LOCATION", "UNFAIR", "GROUND", "MILLION", "SUSPEND", "D'AUBUISSON", "LIVED", "AMMUNITION", "FINDING", "TONIGHT", "PLACES", "NORTHWEST", "EXPLOSIVES", "FOR", "ATTAIN", "PARTICULAR", "INSTITUTIONAL", "REACTION", "WHITE", "OCTOBER", "URBAN", "ACTIVITIES", "PLACED", "ESTIMATED", "CIRCLES", "CARACOL", "OCT", "NEGOTIATION", "SEARCHING", "AMBUSHES", "SPOT", "ATLACATL", "SEIZING", "OFF", "OPPOSITION", "AMBUSHED", "CROWDED", "ASSOCIATED", "ENGINES", "5TH", "CITY", "LIBERTAD", "CLAIMING", "TREATED", "ALAN", "COLUMN", "FRENCH", "DEFINITELY", "DEPARTED", "REPORTS", "RETURNED", "GENEVA", "JANUARY", "UNIT", "DISCUSS", "ASSASSIN", "GASOLINE", "BILATERAL", "READ", "MAYOR", "OIL", "BEHIND", "SPEAKING", "STUCK", "APPARENT", "CONTAINED", "HANDS", "SHARED", "LIBERAL", "CHANGE", "CONFIRM", "ELECTED", "COSTS", "COLOMBIA", "VISIT", "ATTACK", "ELDORADO", "LEAST", "OLD", "OBSERVERS", "POSITION", "DISPOSAL", "RECOVER", "DEPLORABLE", "BRAZIL", "MUNICIPAL", "CHILEANS", "ACTS", "CALM", "CALI", "ATTENDED", "ONE", "HARASSMENT", "EDGAR", "BELONGED", "VALUABLE", "BELTRAN", "HEADS", "FACILITIES", "ACCEPTING", "LEARN", "...", "ENTERPRISE", "REQUEST", "BASQUE", "COMMUNIST", "COMMONLY", "BEHALF", "MEDIATORS", "REVEALS", "HISTORY", "CANO", "CLASS", "TECHNICAL", "LINES", "ACCOUNT", "BURIED", "PERNICIOUS", "SERVED", "WORKING", "PRESUMABLY", "ALLIES", "NAME", "VISTA", "IMPOSED", "GAS", "EXPERIENCE", "WHETHER", "BOMB", "ACROSS", "CONTROL", "NARINO", "OFFICIALS", "POSITIVE", "GEORGE", "FBIS", "WELL-KNOWN", "SIGNED", "SALVADORANS", "LEFT-WING", "NORTHEAST", "SERVING", "APPROACH", "GREEN", "POSSESSION", "UNHARMED", "URGENT", "DUTY", "HITTING", "MEDELLIN", "CARS", "CARD", "YARD", "FAILED", "HOSTED", "CAST", "LITTLE", "OUR", "GEN", "CONTAIN", "GET", "BRIGADE", "ADVANCE", "PERSECUTION", "SECRET", "STOLEN", "REFERENDUM", "SENATOR", "MOTIVE", "BORDERS", "MORE", "LIVING", "LIBERTY", "OQUELI", "TRAFFICKER", "CLANDESTINE", "AUXILIARY", "BRIEF", "0200", "OWNERS", "BOTH", "REGIONAL", "DIFFERENT", "TRIED", "KIND", "AYUTUXTEPEQUE", "HEADING", "GOMEZ", "TREASURY", "15-YEAR-OLD", "SECONDLY", "CHALATENANGO", "ADDS", "HUANCAYO", "MOVE", "RESULT", "ELIANA", "IMPLEMENTED", "UNDETERMINED", "ECUADOR", "PUNISHMENT", "BLACK", "SLATED", "POLICE", "CONTINUING", "METHODS", "GMT", "BLINDFOLDED", "POLICY", "MAKING", "NATIONS", "NATIONALITY", "FAMILY", "SURROUNDED", "FREDDY", "VICTORIES", "GOD", "JOINT", "BARCO", "POWER", "EMBASSY", "GENTLEMEN", "DRIVER", "PAZ", "NORTH", "CONSTANTLY", "RESPONSIBLE", "STATION", "TOTALLY", "BENITO", "INDEPENDENCE", "INDIVIDUAL", "CENTURY", "STUDENT", "EXERCISES", "TERRORISTS", "MORTARS", "MEETING", "KIDNAPPING", "BOARD", "JOIN", "CONTACTED", "IMAGE", "FOUNDED", "INTERIOR", "WHICH", "SOUTH", "DIGNITY", "6TH", "AMARU", "REGION", "HILDA", "CONGRESSMEN", "NARCOTERRORISTS", "SUBVERSIVE", "RESCUED", "PARDON", "NEWSCAST", "ENGINEER", "REITERATED", "SAYING", "COUNTERINSURGENCY", "DEMOBILIZE", "FACTORS", "LARGEST", "INCOME", "WINDOWS", "PURPOSE", "MONTANO", "INTERVENTION", "MATERIAL", "EFFORTS", "GETTING", "JORGE", "ASSEMBLY", "USELESS", "WESTERN", "ALONG", "RECEIVE", "BLASTS", "MODERATION", "ANALYSTS", "NEGOTIATE", "COMMUNITIES", "SEVERELY", "SOURCES", "YSKL", "CONFESSED", "STARTED", "ENJOYING", "FREEDOM", "LOGISTICS", "UNABLE", "MENTIONING", "MIDNIGHT", "ERNESTO", "UNAWARE", "CENTER", "NEEDS", "CALMLY", "ATTACKED", "SONORA", "CONFISCATED", "HILL", "VAST", "FACTOR", "STREET", "PREVENT", "JOSE", "HAS", "POSITIVELY", "PAYING", "CONTINUES", "TARGET", "WANTED", "QUANTITY", "GREETINGS", "DELEGATION", "REPORTERS", "SEVERAL", "FENASTRAS", "SOUTHERN", "SPECIFIC", "CONGRESSMAN", "YES", "CHARGES", "PEACE", "PANIC", "CAMPUS", "BRAVELY", "HOMILY", "HER", "REPUBLICA", "INAUGURATION", "ACTUALLY", "RESUMPTION", "MPSC", "SATURDAY", "FORTUNATELY", "INDICATES", "TELEPHONE", "GALLONS", "GOAL", "STRENGTHEN", "WITHOUT", "FATHERLAND", "KEEPING", "SMUGGLING", "FLAG", "OCCUPY", "0300", "SPREAD", "CAMPAIGN", "COWARDLY", "SITE", "FAILURE", "HIT", "INTERVENE", "VERSION", "NEARBY", "LEAD", "STICKS", "STRICTLY", "SUPPORT", "DENSELY", "ARMING", "GUARDS", "ESCOBAR", "SHAKEN", "CONDUCTED", "COMMENTING", "SIGNING", "BRAVO", "SUNDAY", "INDISCRIMINATE", "GRENADES", "JOURNALISTS", "PENTAGON", "SAID", "MERELY", "WEEK", "FORMS", "THROUGHOUT", "TRUCKS", "WHILE", "UNDERSTANDING", "ENTERPRISES", "SURPRISE", "YESTERDAY", "EVERYBODY", "MURDERER", "SAKE", "HALF", "COMING", "REGRETTED", "SIMULTANEOUS", "LEFT", "REFERS", "RELEASE", "ATMOSPHERE", "HOY", "SAME", "DETERMINED", "COVER", "CHANGED", "STRIKES", "NARCOTICS", "HAND", "SMALL", "TURN", "KILLED", "REACTIONS", "2100", "CENTENO", "MARTA", "NATURE", "OFFICE", "ELIMINATE", "RELIGIOUS", "RALLIES", "REPRESSION", "AUTONOMOUS", "CAPTURE", "TANDONA", "LIGHT", "NACIONAL", "PATRICIA", "GONE", "FLMN", "MOVEMENT", "ACTIVELY", "POINTED", "WELL", "YOUNG", "WAGED", "ROOM", "EVERY", "COLOMBIAN", "ENFORCEMENT", "ESTRADA", "COUNTERATTACK", "AGREE", "LEON", "WENT", "ARRIVE", "MATTERS", "MONSIGNOR", "COMMENT", "CONFERENCE", "RIDICULOUS", "FIRST", "ROSA", "INSURRECTION", "DESTROYED", "NORMAL", "LEGISLATIVE", "IDENTIFY", "DOORS", "DETAILS", "WEST", "FUEL", "VISITED", "PROVOKED", "WERE", "SOLDIERS", "BELONG", "NEGATIVE", "JANEIRO", "LOCATED", "PERSONS", "LEAFLETS", "ACCOMPLICES", "PARATROOPERS", "BELIEVED", "ZACAMIL", "RIGHTIST", "MANEUVER", "ASSISTANT", "ROSALES", "PRO-CASTROITE", "CONCLUDED", "INCREASE", "TOWNSHIP", "CATAPULTS", "KNOWLEDGE", "NORTHEASTERN", "PREPARING", "HELPING", "EXPLOSIVE", "WITHDRAWN", "BOLIVAR", "GROUP", "DOES", "ASSAULT", "ALTHOUGH", "DELGADO", "SOYAPANGO", "CONTROLS", "CAPTURED", "THREATS", "BRITISH", "TEAM", "UNION", "COMMANDOS", "PACKAGE", "CORRESPONDENT", "THESE", "DIEGO", "FULL", "DEALT", "CIVILIZED", "TAIWAN", "BLAME", "PETITION", "SURROUNDING", "HAPPY", "EXPECT", "SECTOR", "MOUNTAINOUS", "UNDERWAY", "PERSONNEL", "FILLED", "INSURGENT", "SANTANDER", "MONITORING", "VICTIMS", "CAUSED", "CORRUPTION", "INDUSTRIALIZED", "BODYGUARD", "EXCHANGE", "FIRES", "BATTALIONS", "LEADING", "SOLUTIONS", "RESIDENTIAL", "SYMBOL", "SIERRA", "ARMORED", "CAUSES", "FUSE", "REMAINED", "PRINCIPLE", "MANUEL", "ESCALATION", "DECIDED", "PRELIMINARY", "NAMED", "ZONE", "UNITY", "POWERFUL", "CONFRONTING", "YOURS", "INCLUDING", "UNITS", "MOVING", "DIFFICULT", "ACCEPT", "RESTRICTED", "BUILDING", "FIRMLY", "EAST", "DETERMINE", "PEDRO", "REVEALED", "UNFAVORABLE", "DECEMBER", "CLAIMED", "CANAL", "COMPLETELY", "COUNTRIES", "UNIFORM", "TECLA", "CANAS", "HEART", "EMPLOYEES", "SOMETHING", "PAST", "RCN", "ANDRES", "TURBAY", "AGREEMENTS", "REITERATE", "DISTRICT", "BEGAN", "DAUGHTER", "SIMON", "RED", "250,000", "ACT", "MINE", "DOWN", "INFORMED", "UNREST", "FOUND", "ENERGY", "CONSERVATIVE", "EARLY", "8TH", "SQUAD", "AK-47", "HEAVY", "APPROPRIATE", "GUATEMALA", "FOREIGNER", "SPILL", "PRESERVE", "SANTIAGO", "AFP", "DOCUMENTS", "LABORATORIES", "SOVIET", "VALLE", "CONDUCTING", "AGO", "NORMALIZED", "OTHERS", "RIO", "BACK", "TELEPHONES", "PROTEST", "RECEIVING", "TEXT", "ALMOST", "LEFTIST", "NATIONAL", "AIM", "FORCED", "TRAIN", "BORDER", "VALDIVIESO", "PARLIAMENT", "ANNOUNCED", "SANDINO", "POSSIBILITY", "TOWERS", "METERS", "PRAVDA", "REVOLUTIONARY", "ESCALON", "COVERING", "ANYWHERE", "SUBVERSIVES", "CONVERSATIONS", "DENYING", "PUNISH", "ALIAS", "VIOLATED", "MINUTE", "MAIN", "OUTLAWED", "PRICE", "TELAM", "GILDA", "MARTINEZ", "ROUND", "INITIAL", "ANY", "BARONS", "PAPER", "DOWNTOWN", "100", "PROPAGANDA", "103", "REDUCTION", "JAN", "ENABLED", "WEAPONS", "OWNED", "COUNTERPART", "MEDIATOR", "EXCERPTS", "MORMON", "CONSIDERATION", "INCLUDE", "PRIOR", "PALACE", "PARKED", "OBTAIN", "DECREED", "SPECIFY", "CONVERGENCE", "BAKER", "FELL", "OSVALDO", "BELLOSO", "REPRESENT", "OPEN", "MARCO", "EXPLOSIONS", "MARCH", "LUISA", "FACED", "ROUTE", "DIFFERENTLY", "PERUVIANS", "150", "CARRIERS", "VICINITY", "BROKEN", "GUERILLAS", "CHIEFS", "PROTECTION", "PROPERTY", "FELT", "GUARANTEES", "RIFLES", "SLOWLY", "DYNAMITE", "LOOK", "MARIO", "VIOLATE", "OPERATIONS", "CONFRONTATION", "PROTECTING", "MASK", "ADOPTED", "0500", "ARTILLERY", "EXECUTIVE", "CITIZEN", "STEP", "FEDERAL", "SOACHA", "MARK", "MRTA", "SECURE", "PRESIDENCY", "INTELLIGENCE", "NICARAGUA", "WORD", "SQUARE", "HURTING", "UNDERTAKEN", "GRADUATING", "DIARIO", "LOSE", "SO-CALLED", "ITALIAN", "LOTS", "PUPPET", "BENJAMIN", "RADIO", "DEVICES", "MEXICAN", "SPECIAL", "HEADQUARTERS", "MAZA", "SERIOUSLY", "INFANTRY", "FIGHTING", "JUNIOR", "NOTIMEX", "DECREES", "SAN", "FESTIVITIES", "SAW", "BASIC", "RESERVATIONS", "BASIN", "6-HOUR", "BASIS", "GROUNDS", "UNIDENTIFIED", "FRUIT", "NECESSARILY", "LEGALLY", "GENERATE", "CIVILIAN", "THEMSELVES"));

	private static AbstractSequenceClassifier<CoreLabel> classifier = null;

	public static void main(String[] args) {





		try {
			 FileInputStream in_file = new FileInputStream("./dict.ser");
			 ObjectInputStream in = new ObjectInputStream(in_file);
			 dict = (HashMap<String, Integer>) in.readObject();
			 in.close();
			 in_file.close();
/*
			 in_file = new FileInputStream("./sentence_probs_adv/prob_vic_adv.ser");
			 in = new ObjectInputStream(in_file);
			 dict = (HashMap<String, Integer>) in.readObject();
			 in.close();
			 in_file.close();
*/

			 classifier=CRFClassifier.getClassifier("./english.all.3class.distsim.crf.ser.gz");
		} catch (IOException e) {
			 e.printStackTrace();
			 return;
		} catch (ClassNotFoundException e) {
			 return;
		}

		Scanner input_scanner = null;
    Scanner ans_scanner = null;
		PrintWriter  writer = null;
		//try {input_scanner = new Scanner(new File(args[0]));}

/*
		ArrayList<ArrayList<ArrayList <Word> > > articles=new ArrayList<ArrayList<ArrayList<Word > > >();
		ArrayList<ArrayList<String[]> > art_ans_weapon=new ArrayList<ArrayList<String[]> >();//2
		ArrayList<ArrayList<String[]> > art_ans_indv=new ArrayList<ArrayList<String[]> >();//3
		ArrayList<ArrayList<String[]> > art_ans_org=new ArrayList<ArrayList<String[]> >();//4
		ArrayList<ArrayList<String[]> > art_ans_tar=new ArrayList<ArrayList<String[]> >();//5
		ArrayList<ArrayList<String[]> > art_ans_vic=new ArrayList<ArrayList<String[]> >();//6
		*/
		try {
			//input_scanner = new Scanner(new File("input.txt"));
  		//ans_scanner = new Scanner(new File("output.txt"));



			//input_scanner = new Scanner(new File("testset1-input.txt"));
      //ans_scanner = new Scanner(new File("testset1-anskeys.txt"));

			input_scanner = new Scanner(new File("DEV_ALL"));
      ans_scanner = new Scanner(new File("ANS_ALL"));

			//writer = new PrintWriter("input.txt.template");
		}
		catch (FileNotFoundException e) {e.printStackTrace();}


		MaxentTagger tagger = new MaxentTagger("./english-left3words-distsim.tagger");
		LexicalizedParser parsnip = LexicalizedParser.loadModel("englishPCFG.ser");
		Properties props = new Properties();
		props.put("annotators", "tokenize, ssplit, truecase");
		StanfordCoreNLP pipeline = new StanfordCoreNLP(props);

		// Go through all articles
		String next_article_name = "";
		String current_article_name = "";
		boolean done_with_stuff=false;
		while(!done_with_stuff){
			String the_article="";
			boolean next_article_found=false;
			while(input_scanner.hasNextLine() &&! next_article_found){
				String next_line = input_scanner.nextLine();

				if(next_line.matches("(DEV-MUC3-[0-9]{4}.*)|(TST1-MUC3-[0-9]{4}.*)|(TST2-MUC4-[0-9]{4}.*)")){
					next_article_found=true;
					current_article_name = next_article_name;
					next_article_name = next_line;
				}
				else
					the_article += next_line;
			}
			if(!next_article_found){
				done_with_stuff = true;
				current_article_name = next_article_name;
			}

			if(!the_article.equals("")){
        String ans_id="";//0
        String ans_inc="";//1
        ArrayList<String[]> ans_weapon=new ArrayList<String[]>();//2
        ArrayList<String[]> ans_indv=new ArrayList<String[]>();//3
        ArrayList<String[]> ans_org=new ArrayList<String[]>();//4
        ArrayList<String[]> ans_tar=new ArrayList<String[]>();//5
        ArrayList<String[]> ans_vic=new ArrayList<String[]>();//6
        boolean ans_found=false;
        boolean ans_done=false;
        int ans_count=0;

				// GET THE ID
				String ID = current_article_name.substring(0, 14);
				if(ID.charAt(0) == 'D'){
					ID = ID.substring(0, 13);
        }
				//System.out.println(ID);


        while(ans_scanner.hasNextLine() &&! ans_done){
    				String next_line = ans_scanner.nextLine();
            String[] things;
            if(ans_found){
              if(next_line.trim().length()==0){
                ans_done=true;
              }
              else{
                if(next_line.charAt(0)!=' '){
                  ans_count++;
                }
                String consider=next_line.substring(16);
                switch(ans_count){
                  case 1:
                        ans_inc=consider;
                        break;
                  case 2:
                        things=consider.split("/");
                        for(int counter=0; counter<things.length; counter++){
                          ans_weapon.add((things[counter]).split(" "));
                        }
                        break;
                  case 3:
                        things=consider.split("/");
                        for(int counter=0; counter<things.length; counter++){
                          ans_indv.add((things[counter]).split(" "));
                        }
                        break;
                  case 4:
                        things=consider.split("/");
                        for(int counter=0; counter<things.length; counter++){
                          ans_org.add((things[counter]).split(" "));
                        }
                        break;
                  case 5:
                        things=consider.split("/");
                        for(int counter=0; counter<things.length; counter++){
                          ans_tar.add((things[counter]).split(" "));
                        }
                        break;
                  case 6:
                        things=consider.split("/");
                        for(int counter=0; counter<things.length; counter++){
                          ans_vic.add((things[counter]).split(" "));
                        }
                        break;
                  default:
                        ans_done=true;
                        break;

                }
              }

            }
            else{
              if(ID.equals(next_line.substring(16))){
                ans_id=ID;
                ans_found=true;
              }
            }
    		}

				// SPLIT THE ARTICLE INTO SENTENCES
				Annotation article_with_case = new Annotation(the_article.toLowerCase());
				Reader reader = new StringReader(article_with_case.toString());
				DocumentPreprocessor dp = new DocumentPreprocessor(reader);
				ArrayList<Tree> tag_trees = new ArrayList<Tree>();
				ArrayList<ArrayList<Word>> noun_phrases=new ArrayList<ArrayList<Word>>();

				//ArrayList<String> ignore_vic = new ArrayList<String>(Arrays.asList("HER", "PRESIDENTIAL", "SEVERAL", "KILLED", "10", "THAT", "ONE", "WAS",  "TWO", "FIVE", "SIX", "BY", "IS", "AS", "AT", "ON", "TO", "THIS","AND", "THE", "OF", "A", "IN", "", "-", "-LSB-", "-RSB-", "-RRB-", "-LRB-", "", ",", ";", ".", "'S", "--", "``"));

				if(ans_inc.equals("ARSON")){
					for (List<HasWord> sentence : dp){
						update_freq_count(freq_arson, sentence, ans_inc, ignore_arson, 8);
					}
				}
				else if(ans_inc.equals("BOMBING")){
					for (List<HasWord> sentence : dp){
						update_freq_count(freq_bombing, sentence, ans_inc, ignore_bombing, 8);
					}

				}
				else if(ans_inc.equals("KIDNAPPING")){
					for (List<HasWord> sentence : dp){
						update_freq_count(freq_kidnapping, sentence, ans_inc, ignore_kidnapping, 8);
					}

				}
				else if(ans_inc.equals("ROBBERY")){
					for (List<HasWord> sentence : dp){
						update_freq_count(freq_robbery, sentence, ans_inc, ignore_robbery, 8);
					}

				}
				else{//interpret this as attack
					for (List<HasWord> sentence : dp){
						update_freq_count(freq_attack, sentence, ans_inc, ignore_attack, 8);
					}

				}


			}
		}

		//SAVE ALL THE THINGS
		/*
		HashMap<String, Double> prob_weapon=terrible_converter(freq_weapon, 0, 0);
		HashMap<String, Double> prob_vic=terrible_converter(freq_vic, 0, 0);
		HashMap<String, Double> prob_tar=terrible_converter(freq_tar, 0, 0);
		HashMap<String, Double> prob_org=terrible_converter(freq_org, 0, 0);
		HashMap<String, Double> prob_indv=terrible_converter(freq_indv, 0, 0);
		*/
		HashMap<String, Double> prob_arson=terrible_converter(freq_arson, 0, 0);
		HashMap<String, Double> prob_attack=terrible_converter(freq_attack, 0, 0);
		HashMap<String, Double> prob_bombing=terrible_converter(freq_bombing, 0, 0);
		HashMap<String, Double> prob_kidnapping=terrible_converter(freq_kidnapping, 0, 0);
		HashMap<String, Double> prob_robbery=terrible_converter(freq_robbery, 0, 0);
    try {
      FileOutputStream fileOut = new FileOutputStream("./sentence_probs_adv/prob_arson.ser");
      ObjectOutputStream out = new ObjectOutputStream(fileOut);
      out.writeObject(prob_arson);
      out.close();
      fileOut.close();
    } catch (IOException e) {
      e.printStackTrace();
    }
		try {
			FileOutputStream fileOut = new FileOutputStream("./sentence_probs_adv/prob_attack.ser");
			ObjectOutputStream out = new ObjectOutputStream(fileOut);
			out.writeObject(prob_attack);
			out.close();
			fileOut.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		try {
			FileOutputStream fileOut = new FileOutputStream("./sentence_probs_adv/prob_bombing.ser");
			ObjectOutputStream out = new ObjectOutputStream(fileOut);
			out.writeObject(prob_bombing);
			out.close();
			fileOut.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		try {
			FileOutputStream fileOut = new FileOutputStream("./sentence_probs_adv/prob_kidnapping.ser");
			ObjectOutputStream out = new ObjectOutputStream(fileOut);
			out.writeObject(prob_kidnapping);
			out.close();
			fileOut.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		try {
			FileOutputStream fileOut = new FileOutputStream("./sentence_probs_adv/prob_robbery.ser");
			ObjectOutputStream out = new ObjectOutputStream(fileOut);
			out.writeObject(prob_robbery);
			out.close();
			fileOut.close();
		} catch (IOException e) {
			e.printStackTrace();
		}

	}

	private static HashMap<String, Double> terrible_converter(HashMap<String, Freq_tuple> input, int cut_off, double min_val){
		HashMap<String, Double> prob=new HashMap<>();
		for(String s: input.keySet()){
			prob.put(s, input.get(s).get_doub(cut_off, min_val));
		}
		//System.out.println(prob.size()+"   "+input.size());
		return prob;
	}

	private static void update_freq_count(HashMap<String, Freq_tuple> freq, List<HasWord> sentence, String ans_, ArrayList<String> ignore_words, int range){

		for(HasWord word: sentence){
			if(ignore_words.contains(word.word().toUpperCase())){

			}
			else{
				if(freq.containsKey(word.word().toUpperCase())){
					freq.get(word.word().toUpperCase()).inc_both();
				}
				else{
					freq.put(word.word().toUpperCase(), new Freq_tuple(1, 1));
				}
			}
		}
	}

}
